"""The full ISO-4217 currency vocabulary (generated by scripts/gen_currencies.py).

Guards that every generated jurisdiction module imports, carries correct
metadata, and uses the authoritative ISO 4217 minor-unit scale (NOT babel/CLDR
display precision, which diverges for some currencies).
"""
import importlib
import os
import tempfile

import pytest

from clausal.modules.countries._data import CURRENCIES, JURISDICTIONS

# Authoritative ISO 4217 minor-unit exceptions; everything else is 2.
ISO_SCALE0 = {"BIF", "CLP", "DJF", "GNF", "ISK", "JPY", "KMF", "KRW", "PYG",
              "RWF", "UGX", "VND", "VUV", "XAF", "XOF", "XPF"}
ISO_SCALE3 = {"BHD", "IQD", "JOD", "KWD", "LYD", "OMR", "TND"}


def _iso_scale(code):
    return 0 if code in ISO_SCALE0 else 3 if code in ISO_SCALE3 else 2


class TestFullVocabulary:
    def test_every_currency_module_imports_with_correct_metadata(self):
        problems = []
        for r in CURRENCIES:
            mod = importlib.import_module(f"clausal.modules.countries.{r['jurisdiction']}")
            obj = getattr(mod, r["name"], None)
            if obj is None:
                problems.append(("missing", r)); continue
            if not (obj.is_currency and obj.iso_code == r["code"]
                    and obj.scale == r["scale"] and obj._dims == {obj: 1}):
                problems.append(("metadata", r))
        assert not problems, problems[:5]

    def test_scales_match_iso_4217(self):
        wrong = [(r["code"], r["scale"], _iso_scale(r["code"]))
                 for r in CURRENCIES if r["scale"] != _iso_scale(r["code"])]
        assert not wrong, wrong

    def test_jurisdictions_unique_and_one_currency_each(self):
        js = [r["jurisdiction"] for r in CURRENCIES]
        assert len(js) == len(set(js))
        assert set(js) == set(JURISDICTIONS)

    def test_spot_check_known_currencies(self):
        # (jurisdiction, name, code, scale)
        expect = [
            ("thailand", "baht", "THB", 2),
            ("south_korea", "won", "KRW", 0),
            ("kuwait", "dinar", "KWD", 3),
            ("india", "rupee", "INR", 2),
            ("switzerland", "franc", "CHF", 2),
            ("united_kingdom", "sterling", "GBP", 2),
        ]
        for j, name, code, scale in expect:
            obj = getattr(importlib.import_module(f"clausal.modules.countries.{j}"), name)
            assert (obj.iso_code, obj.scale) == (code, scale), (j, name)

    def test_new_currency_end_to_end_in_clausal(self):
        from clausal.import_hook import _load_module
        from clausal.logic.solve import call
        d = tempfile.mkdtemp()
        p = os.path.join(d, "vocab.clausal")
        with open(p, "w") as f:
            f.write("-import_from(thailand, [baht])\n"
                    "-import_from(currency, [money_str])\n"
                    "Test(S) <- (eval_(19.99(baht), A), eval_(0.01(baht), B), "
                    "eval_(A + B, C), money_str(C, half_up, S))\n")
        mod = _load_module("vocab", p).__dict__["$module"]
        from clausal.logic.variables import Var, deref
        v = Var()
        got = None
        for _ in call("Test", v, module=mod):
            got = deref(v); break
        assert got == "20.00 THB"

    def test_zero_scale_currency_rejects_fraction(self):
        from clausal.terms import Quantity, CurrencyPrecisionError
        from clausal.modules.countries.south_korea import won
        with pytest.raises(CurrencyPrecisionError):
            Quantity(1000.5, won)
