"""Generate the ``library(...)`` ``.seam`` facades over the engine's Python
modules.

Clausal Prolog reaches Python ONLY through ``.seam`` modules (operator
rulings, 2026-10-01), and imports a facade the Scryer way, as a system
library::

    :- use_module(library(datetime), [date_add/3, days_between/3]).
    :- use_module(library(countries/european_union), [euro]).

Every Python module a ``use_module`` in Prolog text can resolve to under
``clausal/modules`` gets one, at the same path below ``clausal/library``
(the ``py/`` level dropped)::

    clausal/modules/py/datetime.py               -> library(datetime)
    clausal/modules/units.py (and py/units.py)   -> library(units)
    clausal/modules/countries/european_union.py  -> library(countries/european_union)

A facade is a pure re-export, no clauses of its own: the module's
PREDICATES (:func:`clausal.module_signatures`, same names and arities) and
its VALUES (units, currencies, quantities and numeric constants, which a
``.pl`` imports by bare name: ``use_module(european_union, [euro])``).  A
``py/<lib>`` file that only star-imports the module of the same name one
level up (``py/units.py``, ``py/imperial.py``) shares that module's
facade.  A module offering neither (``prolog``: evaluation helpers for
qualified seam calls; the ``countries`` package itself) gets none.

The facades are GENERATED and committed; a test checks that the committed
files are exactly this script's output.  Regenerate after adding or
changing an engine module's predicates or values::

    python -m clausal.tools.gen_library_facades           # rewrite
    python -m clausal.tools.gen_library_facades --check   # exit 1 on drift
    python -m clausal.tools.gen_library_facades --census  # the table

``--modules`` / ``--out`` point the script at an extension distribution's
``.../clausal/modules`` directory and a facade directory of its own.
"""
from __future__ import annotations

import argparse
import importlib
import os
import sys

#: The engine's module directory and the facade directory, in this tree.
_HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULES_DIR = os.path.join(_HERE, "modules")
FACADES_DIR = os.path.join(_HERE, "library")

#: The dotted packages the two directories are.
MODULES_PACKAGE = "clausal.modules"
FACADE_PACKAGE = "clausal.library"

#: The facades' file extension: the seam is the Python-interop surface.
FACADE_SUFFIX = ".seam"

#: The import-free capability index the script also writes: the
#: ``library(...)`` names that have a facade, readable without the engine.
INDEX_PATH = os.path.join(_HERE, "_py_facades.py")

_INDEX = '''"""The ``library(...)`` names that have a ``.seam`` facade over an engine
Python module (GENERATED by clausal/tools/gen_library_facades.py -- do not
edit; regenerate).

Clausal Prolog reaches these Python libraries as library(<name>). Direct
py/<lib> imports are refused for the clausal_prolog surface, which is active
only when _suffixes.CLAUSAL_PROLOG_SUFFIXES is non-empty.

This module has no imports on purpose: a consumer reads the capability
without importing the engine.
"""

#: Each name is what ``:- use_module(library(<name>), [...]).`` spells;
#: the facade is ``clausal/library/<name>.seam``.
PY_FACADE_LIBS: tuple[str, ...] = (
{entries})
'''

#: The sub-packages of ``clausal/modules`` whose files are modules a
#: ``use_module`` names (``py`` is dropped from the facade path).
_SUBPACKAGES = ("py", "countries")

_HEADER = """\
# GENERATED by clausal/tools/gen_library_facades.py -- do not edit;
# regenerate.  The .seam facade over the Python module
#     {source}
# Clausal Prolog reaches Python only through a .seam module, so it
# imports this one:
#     :- use_module(library({lib}), [{example}]).
# A pure re-export of the module's {what}, same names{arities}.
"""


def offer(mod) -> "tuple[dict, list[str]]":
    """``(predicate signatures, sorted value names)`` of module *mod*."""
    from clausal.library import is_value  # noqa: PLC0415
    from clausal.logic.solve import module_signatures  # noqa: PLC0415
    sig = module_signatures(mod)
    values = sorted(n for n, v in vars(mod).items()
                    if not n.startswith("_") and n not in sig
                    and is_value(v))
    return sig, values


def sources(modules_dir: str = MODULES_DIR) -> "list[tuple[str, str, list]]":
    """``(facade path, source dotted module, [every dotted spelling that
    resolves to it])`` for each engine Python module under *modules_dir*,
    sorted by facade path.  ``py/X`` folds into ``X`` when ``X.py`` exists
    one level up (its compatibility shim)."""
    def names(d):
        if not os.path.isdir(d):
            return []
        return sorted(f[:-3] for f in os.listdir(d)
                      if f.endswith(".py") and not f.startswith("_"))
    out: dict[str, tuple[str, list]] = {}
    for n in names(modules_dir):
        out[n] = (f"{MODULES_PACKAGE}.{n}", [f"{MODULES_PACKAGE}.{n}"])
    for sub in _SUBPACKAGES:
        for n in names(os.path.join(modules_dir, sub)):
            dotted = f"{MODULES_PACKAGE}.{sub}.{n}"
            path = n if sub == "py" else f"{sub}/{n}"
            if path in out:
                out[path][1].append(dotted)
            else:
                out[path] = (dotted, [dotted])
    return [(p, src, spellings) for p, (src, spellings) in sorted(out.items())]


def facade_text(path: str, source: str, sig: dict,
                values: list) -> "str | None":
    """The facade source re-exporting *sig* and *values* from the module
    *source*, for ``library(<path>)``; None when it offers nothing."""
    if not sig and not values:
        return None
    entries = []
    for name in sorted(sig):
        arities = sig[name]
        if not arities:
            raise ValueError(
                f"{source}: {name} is a predicate whose arities cannot be "
                f"read (its dispatch takes *args); give it a _dispatch_fns "
                f"table so a facade can export name/N")
        entries.extend(f"{name}/{a}" for a in sorted(arities))
    what = " and ".join(w for w, have in (("predicates", sig),
                                          ("values", values)) if have)
    lines = [_HEADER.format(
        source=source, lib=path, example=(entries or values)[0], what=what,
        arities=" and arities" if sig else "")]
    module_name = path.rsplit("/", 1)[-1]
    if entries:
        lines.append(f"-module({module_name}, [\n")
        lines.extend(f"    {e},\n" for e in entries)
        lines.append("])\n")
    else:
        lines.append(f"-module({module_name}, [])\n")
    lines.append(f"-import_from({source}, [\n")
    lines.extend(f"    {n},\n" for n in sorted([*sig, *values]))
    lines.append("])\n")
    return "".join(lines)


def census(modules_dir: str = MODULES_DIR) -> "list[dict]":
    """One row per engine Python module: its facade path (None: no
    facade), the source it wraps, its spellings, and its offer."""
    rows = []
    for path, source, spellings in sources(modules_dir):
        mod = importlib.import_module(source)
        sig, values = offer(mod)
        for other in spellings:
            if other == source:
                continue
            o_sig, o_values = offer(importlib.import_module(other))
            if (o_sig, o_values) != (sig, values):
                raise ValueError(
                    f"{other} and {source} both map to library({path}) but "
                    f"offer different predicates or values")
        rows.append({
            "path": path if (sig or values) else None,
            "source": source, "spellings": spellings,
            "predicates": sum(len(a) for a in sig.values()),
            "values": len(values), "sig": sig, "value_names": values,
        })
    return rows


def generate(modules_dir: str = MODULES_DIR) -> dict[str, str]:
    """``{relative file path: source}`` of every facade the modules in
    *modules_dir* call for."""
    out = {}
    for row in census(modules_dir):
        if row["path"] is None:
            continue
        text = facade_text(row["path"], row["source"], row["sig"],
                           row["value_names"])
        out[row["path"] + FACADE_SUFFIX] = text
    return out


def index_text(facades: "dict[str, str]") -> str:
    """The source of ``clausal/_py_facades.py`` for the facade files
    *facades* (``{relative path: source}``)."""
    libs = sorted(f[:-len(FACADE_SUFFIX)] for f in facades)
    return _INDEX.format(entries="".join(f'    "{lib}",\n' for lib in libs))


def committed(out_dir: str = FACADES_DIR) -> dict[str, str]:
    """``{relative file path: source}`` of the facades now in *out_dir*."""
    found = {}
    for root, dirs, files in os.walk(out_dir):
        dirs[:] = sorted(d for d in dirs if d != "__pycache__")
        for f in sorted(files):
            if f.endswith(FACADE_SUFFIX):
                full = os.path.join(root, f)
                rel = os.path.relpath(full, out_dir).replace(os.sep, "/")
                with open(full, encoding="utf-8") as fh:
                    found[rel] = fh.read()
    return found


def main(argv: "list[str] | None" = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="report drift and exit 1 instead of writing")
    ap.add_argument("--census", action="store_true",
                    help="print module -> facade -> counts and exit")
    ap.add_argument("--modules", default=MODULES_DIR,
                    help="the clausal/modules directory (default: the "
                         "engine's)")
    ap.add_argument("--out", default=FACADES_DIR,
                    help="the facade directory (default: clausal/library)")
    ap.add_argument("--index", default=INDEX_PATH,
                    help="the capability index to write (default: "
                         "clausal/_py_facades.py); empty: none")
    args = ap.parse_args(argv)
    if args.census:
        rows = census(args.modules)
        for r in rows:
            lib = f"library({r['path']})" if r["path"] else "(no facade)"
            print(f"{', '.join(r['spellings'])}\t{lib}\t"
                  f"{r['predicates']} predicates\t{r['values']} values")
        made = [r for r in rows if r["path"]]
        print(f"{len(rows)} modules, {len(made)} facades, "
              f"{sum(r['predicates'] for r in made)} predicates, "
              f"{sum(r['values'] for r in made)} values")
        return 0
    want = generate(args.modules)
    have = committed(args.out)
    stale = sorted(set(have) - set(want))
    changed = sorted(f for f in want if have.get(f) != want[f])
    index = index_text(want) if args.index else None
    index_now = None
    if index is not None and os.path.exists(args.index):
        with open(args.index, encoding="utf-8") as fh:
            index_now = fh.read()
    if args.check:
        for f in changed:
            print(f"out of date: {f}", file=sys.stderr)
        for f in stale:
            print(f"no module behind: {f}", file=sys.stderr)
        if index is not None and index_now != index:
            print(f"out of date: {args.index}", file=sys.stderr)
        return 1 if (changed or stale
                     or (index is not None and index_now != index)) else 0
    for f in changed:
        full = os.path.join(args.out, f)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as fh:
            fh.write(want[f])
    for f in stale:
        os.remove(os.path.join(args.out, f))
    if index is not None and index_now != index:
        with open(args.index, "w", encoding="utf-8") as fh:
            fh.write(index)
    print(f"{len(want)} facades ({len(changed)} written, {len(stale)} "
          f"removed) in {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
