"""The ``library(...)`` facades over the engine's Python modules, and the
Clausal Prolog refusal of a Python import target (operator rulings
2026-10-01: Clausal Prolog reaches Python only through ``.seam`` modules,
and imports a facade as ``use_module(library(<lib>), [...])``).

* ``clausal/library/<path>.seam`` re-exports the predicates (same names,
  arities, adapter objects) and the values (units, currencies, numbers) of
  every Python module under ``clausal/modules`` -- ``py/<lib>`` at
  ``library(<lib>)``, ``countries/<j>`` at ``library(countries/<j>)``,
  ``units`` at ``library(units)``; the files and the import-free index
  ``clausal/_py_facades.py`` are generated by
  ``clausal/tools/gen_library_facades.py`` and must match its output.
* ``library(<lib>)`` resolves to the facade, after the libraries the front
  end already knows (built in or mapped), which a facade never shadows.
* Under the ``clausal_prolog`` SURFACE an import whose target is a Python
  module by PATH (``py/<lib>``, ``clausal/modules/units``, any other
  ``.py``) is refused, naming the facade; a module NAME a seam alias
  resolves (``european_union``, ``units``) imports its facade.  That
  surface has no file extension until the extension flip
  (``_suffixes.CLAUSAL_PROLOG_SUFFIXES`` is empty), so these tests force it
  by putting ``.pl`` in that tuple; ``.pl`` and seam files are otherwise
  unchanged, and a ``.pl`` may still import ``py/<lib>`` directly.
"""
from __future__ import annotations

import ast
import importlib
import os
import sys
import textwrap

import pytest

import clausal
from clausal import _py_facades, _suffixes
from clausal.tools import gen_library_facades as gen
from clausal.tools.iso_l3_directives import (
    _BUILTIN_LIBRARIES, _LIBRARY_MODULES)
from clausal.tools.prolog_to_clausal import (
    _BUILTIN_LIBRARIES as _TR_BUILTIN, _LIBRARY_TO_MODULE)

DATES_FACADE = """\
:- module({name}, [gap/1, due/1]).
:- use_module(library(datetime), [date_add/3, timedelta/3, days_between/3]).
gap(N) :- days_between(date(2026, 1, 15), date(2026, 3, 1), N).
due(D) :- timedelta(30, 0, TD), date_add(date(2026, 1, 15), TD, D).
:- end_module({name}).
"""

DATES_DIRECT = DATES_FACADE.replace("library(datetime)", "py/datetime")

MONEY = """\
:- module({name}, [hundred/1, secs/1]).
:- use_module({eu}, [euro, eur_cent]).
:- use_module({units}, [second]).
:- constant_number_units(one_euro, 1, euro).
:- constant_number_units(one_second, 1, second).
hundred(Q) :- Q is 100 * constant(one_euro).
secs(Q) :- Q is 3 * constant(one_second).
:- end_module({name}).
"""

_CENSUS = gen.census()


@pytest.fixture
def clausal_prolog(monkeypatch):
    """Load ``.pl`` files as the Clausal Prolog surface, as the extension
    flip will load ``.clausal`` (``clausal.end_module.surface_of`` reads
    the tuple at each call)."""
    monkeypatch.setattr(_suffixes, "CLAUSAL_PROLOG_SUFFIXES", (".pl",))


def _refusal(native, name, text, **kw):
    with pytest.raises(SyntaxError) as ei:
        native.load(name, textwrap.dedent(text), **kw)
    return str(ei.value)


# ── the facades ──


def test_committed_facades_are_the_generators_output():
    want = gen.generate()
    have = gen.committed()
    assert set(have) == set(want), (sorted(set(have) ^ set(want)))
    for f in want:
        assert have[f] == want[f], (
            f"{f} is stale: run python -m clausal.tools.gen_library_facades")
    # Denominator: every module under clausal/modules but prolog (helpers
    # for qualified seam calls: no predicate, no value) has a facade; the
    # py/ shims py/units and py/imperial share units' and imperial's.
    rows = gen.census()
    assert len(rows) >= 200 and len(want) == len(rows) - 1, len(want)
    assert [r["source"] for r in rows if r["path"] is None] == [
        "clausal.modules.prolog"]
    for lib in ("datetime", "json", "re", "units", "imperial", "currency",
                "countries/european_union"):
        assert lib + gen.FACADE_SUFFIX in want, lib


def test_the_capability_index_matches_the_facade_files():
    libs = sorted(f[:-len(gen.FACADE_SUFFIX)] for f in gen.committed())
    assert list(_py_facades.PY_FACADE_LIBS) == libs
    assert "datetime" in libs and "countries/european_union" in libs
    with open(gen.INDEX_PATH, encoding="utf-8") as fh:
        text = fh.read()
    assert text == gen.index_text(gen.generate())
    # Readable without the engine: the module imports nothing.
    assert not [n for n in ast.walk(ast.parse(text))
                if isinstance(n, (ast.Import, ast.ImportFrom))]
    for lib in libs:
        assert os.path.exists(os.path.join(
            gen.FACADES_DIR, lib + gen.FACADE_SUFFIX)), lib


@pytest.mark.parametrize("row", [r for r in _CENSUS if r["path"]],
                         ids=lambda r: r["path"])
def test_a_facade_is_a_pure_re_export(row):
    source = importlib.import_module(row["source"])
    facade = importlib.import_module(
        "clausal.library." + row["path"].replace("/", "."))
    sig = clausal.module_signatures(source)
    assert clausal.module_signatures(facade) == sig
    for name in [*sig, *row["value_names"]]:
        # The module's object itself: no wrapper, no new behaviour.
        assert getattr(facade, name) is getattr(source, name), name
    for other in row["spellings"]:
        assert clausal.module_signatures(
            importlib.import_module(other)) == sig


def test_no_facade_shadows_a_known_library():
    facades = {f[:-len(gen.FACADE_SUFFIX)] for f in gen.committed()}
    known = (set(_BUILTIN_LIBRARIES) | set(_LIBRARY_MODULES)
             | set(_TR_BUILTIN) | set(_LIBRARY_TO_MODULE))
    assert not facades & known


def test_no_facade_takes_a_scryer_library_name():
    """Operator ruling 2026-10-01: a facade whose name is one of Scryer's
    own libraries is published as library(py_<name>)."""
    from clausal.library import SCRYER_LIBRARIES
    facades = {f[:-len(gen.FACADE_SUFFIX)] for f in gen.committed()}
    assert not facades & SCRYER_LIBRARIES
    clashed = {f[3:] for f in facades if f.startswith("py_")}
    assert clashed == {"csv", "files", "os", "process", "random", "uuid"}
    assert clashed <= SCRYER_LIBRARIES


@pytest.mark.parametrize("frontend", ["native", "translator"])
def test_clausal_prolog_imports_a_py_prefixed_facade(native, ans, frontend,
                                                     clausal_prolog):
    name = f"fac_pyos_{frontend}"
    mod = native.load(name, textwrap.dedent(f"""\
        :- module({name}, [n/1]).
        :- use_module(library(py_os), [cpu_count/1]).
        n(yes) :- cpu_count(C), C > 0.
        :- end_module({name}).
        """), frontend=frontend)
    assert ans(mod, "n") == ["yes"]


def test_a_scryer_library_name_stays_unknown_in_a_pl(native):
    """library(os) is Scryer's library, which Clausal does not provide:
    no facade answers it, so the native front end still refuses it."""
    msg = _refusal(native, "fac_scryer_os",
                   ":- use_module(library(os), [getenv/2]).\n")
    assert "library(os) is not a library" in msg


def test_the_refusal_of_py_os_names_library_py_os(native, clausal_prolog):
    msg = _refusal(native, "fac_no_os", """\
        :- module(fac_no_os, []).
        :- use_module(py/os, [cpu_count/1]).
        :- end_module(fac_no_os).
        """)
    assert "library(py_os)" in msg


def test_a_submodule_named_after_the_stdlib_loads():
    """The stdlib-shadow guard defers only a TOP-LEVEL name: the facade
    ``clausal.library.datetime`` cannot stand in for ``datetime``."""
    import datetime
    mod = importlib.import_module("clausal.library.datetime")
    assert mod.__file__.endswith("datetime.seam")
    assert sys.modules["datetime"] is datetime


# ── YES: Clausal Prolog imports the facade ──


@pytest.mark.parametrize("frontend", ["native", "translator"])
def test_clausal_prolog_imports_the_datetime_facade(native, ans, frontend,
                                                    clausal_prolog):
    name = f"fac_yes_{frontend}"
    mod = native.load(name, DATES_FACADE.format(name=name), frontend=frontend)
    assert ans(mod, "gap") == [-45]
    assert len(ans(mod, "due")) == 1


@pytest.mark.parametrize("frontend", ["native", "translator"])
def test_clausal_prolog_imports_the_re_and_json_facades(native, ans, frontend,
                                                        clausal_prolog):
    name = f"fac_re_json_{frontend}"
    mod = native.load(name, textwrap.dedent(f"""\
        :- module({name}, [m/1, j/1]).
        :- use_module(library(re), [match/2]).
        :- use_module(library(json), [parse/2]).
        m(yes) :- match("a+", "aaa").
        j(V) :- parse("[7, 8]", [V, _]).
        :- end_module({name}).
        """), frontend=frontend)
    assert ans(mod, "m") == ["yes"]
    assert ans(mod, "j") == [7]


def test_a_listless_facade_import_brings_every_predicate(native, ans,
                                                         clausal_prolog):
    mod = native.load("fac_all", textwrap.dedent("""\
        :- module(fac_all, [w/1]).
        :- use_module(library(datetime)).
        w(N) :- days_between(date(2026, 1, 15), date(2026, 3, 1), N).
        :- end_module(fac_all).
        """))
    assert ans(mod, "w") == [-45]


def test_a_wrong_arity_against_a_facade_is_a_load_error(native,
                                                        clausal_prolog):
    # The facade is a seam module: its -import_from checks the indicator
    # when the importer runs (an ImportError naming the .pl line).
    with pytest.raises(ImportError) as ei:
        native.load("fac_arity", textwrap.dedent("""\
            :- module(fac_arity, []).
            :- use_module(library(datetime), [date_add/2]).
            :- end_module(fac_arity).
            """))
    msg = str(ei.value)
    assert "date_add/2" in msg and "date_add/3" in msg


# ── NO: Clausal Prolog importing a Python module directly ──


@pytest.mark.parametrize("frontend", ["native", "translator"])
@pytest.mark.parametrize("lib,pi", [("datetime", "date_add/3"),
                                    ("re", "match/2"), ("json", "parse/2")])
def test_clausal_prolog_refuses_a_py_import(native, frontend, lib, pi,
                                            clausal_prolog):
    name = f"fac_no_{lib}_{frontend}"
    msg = _refusal(native, name, f"""\
        :- module({name}, []).
        :- use_module(py/{lib}, [{pi}]).
        :- end_module({name}).
        """, frontend=frontend)
    assert "permission_error(access, python_module, py." + lib + ")" in msg
    assert f"library({lib})" in msg            # names the facade to use


def test_clausal_prolog_refuses_a_listless_py_import(native, clausal_prolog):
    msg = _refusal(native, "fac_no_all", """\
        :- module(fac_no_all, []).
        :- use_module(py/datetime).
        :- end_module(fac_no_all).
        """)
    assert "library(datetime)" in msg


def test_clausal_prolog_refuses_any_python_module(native, clausal_prolog):
    """Not only py/<lib>: any import target that is a Python file."""
    msg = _refusal(native, "fac_no_other", """\
        :- module(fac_no_other, []).
        :- use_module(clausal/modules/currency, [money/3]).
        :- end_module(fac_no_other).
        """)
    assert "permission_error(access, python_module" in msg
    assert "library(currency)" in msg


def test_a_user_python_module_is_refused(native, clausal_prolog):
    (native.tmp / "fac_user_py.py").write_text("x = 1\n")
    msg = _refusal(native, "fac_no_user", """\
        :- module(fac_no_user, []).
        :- use_module(fac_user_py, [x]).
        :- end_module(fac_no_user).
        """)
    assert "permission_error(access, python_module, fac_user_py)" in msg
    assert "write a .seam wrapper" in msg


def test_an_engine_module_without_a_facade_names_the_generator(
        native, clausal_prolog):
    msg = _refusal(native, "fac_no_prolog", """\
        :- module(fac_no_prolog, []).
        :- use_module(clausal/modules/prolog).
        :- end_module(fac_no_prolog).
        """)
    assert "gen_library_facades" in msg


# ── units and currencies: values through a facade ──


def _money(native, ans, name, eu, units, **kw):
    mod = native.load(name, MONEY.format(name=name, eu=eu, units=units), **kw)
    return ans(mod, "hundred"), ans(mod, "secs")


@pytest.mark.parametrize("frontend", ["native"])
def test_currency_and_unit_values_through_their_facades(native, ans,
                                                        frontend,
                                                        monkeypatch):
    """(Native only: the translator front end does not lower
    constant_number_units/3 with a unit at all, on either surface.)"""
    # The ISO .pl surface, short names: the reference.
    want = _money(native, ans, f"fac_m_pl_{frontend}", "european_union",
                  "units", frontend=frontend)
    assert len(want[0]) == 1 and len(want[1]) == 1
    monkeypatch.setattr(_suffixes, "CLAUSAL_PROLOG_SUFFIXES", (".pl",))
    # YES: Clausal Prolog, the library(...) spelling ...
    assert _money(native, ans, f"fac_m_lib_{frontend}",
                  "library(countries/european_union)", "library(units)",
                  frontend=frontend) == want
    # ... and the short module names, which name the same facades.
    assert _money(native, ans, f"fac_m_short_{frontend}", "european_union",
                  "units", frontend=frontend) == want


@pytest.mark.parametrize("spec,imports,facade", [
    ("european_union", "euro", "clausal.library.countries.european_union"),
    ("library(countries/european_union)", "euro",
     "clausal.library.countries.european_union"),
    ("units", "second", "clausal.library.units"),
    ("date_time", "today/1", "clausal.library.datetime"),
])
def test_the_translator_imports_the_facade(spec, imports, facade):
    from clausal.tools.prolog_to_clausal import prolog_to_clausal
    out = prolog_to_clausal(f":- use_module({spec}, [{imports}]).\n",
                            surface="clausal_prolog")
    name = imports.split("/")[0]
    assert f"-import_from({facade}, [{name}])" in out, out


@pytest.mark.parametrize("frontend", ["native", "translator"])
def test_clausal_prolog_refuses_a_python_module_as_a_library(native,
                                                             frontend,
                                                             clausal_prolog):
    """An unknown library(...) read as a module path must not reach a
    Python module around the rule (the native front end refuses an unknown
    library outright; the translator reads it as a module)."""
    name = f"fac_lib_py_{frontend}"
    with pytest.raises(SyntaxError):
        native.load(name, textwrap.dedent(f"""\
            :- module({name}, []).
            :- use_module(library(clausal/modules/py/datetime),
                          [date_add/3]).
            :- end_module({name}).
            """), frontend=frontend)


@pytest.mark.parametrize("frontend", ["native", "translator"])
def test_clausal_prolog_refuses_a_currency_module_path(native, frontend,
                                                       clausal_prolog):
    name = f"fac_m_no_{frontend}"
    msg = _refusal(native, name, MONEY.format(
        name=name, eu="clausal/modules/countries/european_union",
        units="units"), frontend=frontend)
    assert "library(countries/european_union)" in msg


# ── unchanged: the ISO .pl surface and the seam ──


@pytest.mark.parametrize("frontend", ["native", "translator"])
def test_a_pl_still_imports_py_datetime_directly(native, ans, frontend):
    name = f"fac_pl_{frontend}"
    mod = native.load(name, DATES_DIRECT.format(name=name), frontend=frontend)
    assert ans(mod, "gap") == [-45]
    assert len(ans(mod, "due")) == 1


@pytest.mark.parametrize("frontend", ["native", "translator"])
def test_a_pl_may_import_the_facade_too(native, ans, frontend):
    name = f"fac_pl_lib_{frontend}"
    mod = native.load(name, DATES_FACADE.format(name=name), frontend=frontend)
    assert ans(mod, "gap") == [-45]


def test_a_seam_file_still_imports_py_datetime(native, ans):
    mod = native.load("fac_seam", textwrap.dedent("""\
        -import_from(py.datetime, [date, days_between])
        gap(N) <- days_between(date(2026, 1, 15), date(2026, 3, 1), N)
        """), suffix=".seam")
    assert ans(mod, "gap") == [-45]


def test_the_refusal_is_active_since_the_flip(native):
    """No fixture: a real ``.clausal`` file is Clausal Prolog, so its
    Python import is refused."""
    assert _suffixes.CLAUSAL_PROLOG_SUFFIXES == (".clausal",)
    msg = _refusal(native, "fac_flip_os", """\
        :- module(fac_flip_os, []).
        :- use_module(py/os, [cpu_count/1]).
        :- end_module(fac_flip_os).
        """, suffix=".clausal")
    assert "library(py_os)" in msg
