"""Generated ISO-4217 currency data. Edit scripts/gen_currencies.py, not this."""

CURRENCIES = [
    {"jurisdiction": "afghanistan", "name": "afghani", "code": "AFN", "scale": 2, "symbol": "AFN"},
    {"jurisdiction": "albania", "name": "lek", "code": "ALL", "scale": 2, "symbol": "ALL"},
    {"jurisdiction": "algeria", "name": "dinar", "code": "DZD", "scale": 2, "symbol": "DZD"},
    {"jurisdiction": "angola", "name": "kwanza", "code": "AOA", "scale": 2, "symbol": "AOA"},
    {"jurisdiction": "argentina", "name": "peso", "code": "ARS", "scale": 2, "symbol": "ARS"},
    {"jurisdiction": "armenia", "name": "dram", "code": "AMD", "scale": 2, "symbol": "AMD"},
    {"jurisdiction": "aruba", "name": "florin", "code": "AWG", "scale": 2, "symbol": "AWG"},
    {"jurisdiction": "australia", "name": "dollar", "code": "AUD", "scale": 2, "symbol": "A$"},
    {"jurisdiction": "azerbaijan", "name": "manat", "code": "AZN", "scale": 2, "symbol": "AZN"},
    {"jurisdiction": "bahamas", "name": "dollar", "code": "BSD", "scale": 2, "symbol": "BSD"},
    {"jurisdiction": "bahrain", "name": "dinar", "code": "BHD", "scale": 3, "symbol": "BD"},
    {"jurisdiction": "bangladesh", "name": "taka", "code": "BDT", "scale": 2, "symbol": "BDT"},
    {"jurisdiction": "barbados", "name": "dollar", "code": "BBD", "scale": 2, "symbol": "BBD"},
    {"jurisdiction": "belarus", "name": "ruble", "code": "BYN", "scale": 2, "symbol": "BYN"},
    {"jurisdiction": "belize", "name": "dollar", "code": "BZD", "scale": 2, "symbol": "BZD"},
    {"jurisdiction": "bermuda", "name": "dollar", "code": "BMD", "scale": 2, "symbol": "BMD"},
    {"jurisdiction": "bhutan", "name": "ngultrum", "code": "BTN", "scale": 2, "symbol": "BTN"},
    {"jurisdiction": "bolivia", "name": "boliviano", "code": "BOB", "scale": 2, "symbol": "BOB"},
    {"jurisdiction": "bosnia_herzegovina", "name": "mark", "code": "BAM", "scale": 2, "symbol": "BAM"},
    {"jurisdiction": "botswana", "name": "pula", "code": "BWP", "scale": 2, "symbol": "BWP"},
    {"jurisdiction": "brazil", "name": "real", "code": "BRL", "scale": 2, "symbol": "R$"},
    {"jurisdiction": "brunei", "name": "dollar", "code": "BND", "scale": 2, "symbol": "BND"},
    {"jurisdiction": "bulgaria", "name": "lev", "code": "BGN", "scale": 2, "symbol": "BGN"},
    {"jurisdiction": "burundi", "name": "franc", "code": "BIF", "scale": 0, "symbol": "BIF"},
    {"jurisdiction": "cambodia", "name": "riel", "code": "KHR", "scale": 2, "symbol": "KHR"},
    {"jurisdiction": "canada", "name": "dollar", "code": "CAD", "scale": 2, "symbol": "CA$"},
    {"jurisdiction": "cape_verde", "name": "escudo", "code": "CVE", "scale": 2, "symbol": "CVE"},
    {"jurisdiction": "cayman_islands", "name": "dollar", "code": "KYD", "scale": 2, "symbol": "KYD"},
    {"jurisdiction": "central_african_cfa", "name": "franc", "code": "XAF", "scale": 0, "symbol": "FCFA"},
    {"jurisdiction": "cfp_franc", "name": "franc", "code": "XPF", "scale": 0, "symbol": "CFPF"},
    {"jurisdiction": "chile", "name": "peso", "code": "CLP", "scale": 0, "symbol": "CLP"},
    {"jurisdiction": "china", "name": "yuan", "code": "CNY", "scale": 2, "symbol": "CN¥"},
    {"jurisdiction": "colombia", "name": "peso", "code": "COP", "scale": 2, "symbol": "COP"},
    {"jurisdiction": "comoros", "name": "franc", "code": "KMF", "scale": 0, "symbol": "KMF"},
    {"jurisdiction": "congo_kinshasa", "name": "franc", "code": "CDF", "scale": 2, "symbol": "CDF"},
    {"jurisdiction": "costa_rica", "name": "colon", "code": "CRC", "scale": 2, "symbol": "CRC"},
    {"jurisdiction": "cuba", "name": "peso", "code": "CUP", "scale": 2, "symbol": "CUP"},
    {"jurisdiction": "czechia", "name": "koruna", "code": "CZK", "scale": 2, "symbol": "CZK"},
    {"jurisdiction": "denmark", "name": "krone", "code": "DKK", "scale": 2, "symbol": "DKK"},
    {"jurisdiction": "djibouti", "name": "franc", "code": "DJF", "scale": 0, "symbol": "DJF"},
    {"jurisdiction": "dominican_republic", "name": "peso", "code": "DOP", "scale": 2, "symbol": "DOP"},
    {"jurisdiction": "east_caribbean", "name": "dollar", "code": "XCD", "scale": 2, "symbol": "EC$"},
    {"jurisdiction": "egypt", "name": "pound", "code": "EGP", "scale": 2, "symbol": "EGP"},
    {"jurisdiction": "eritrea", "name": "nakfa", "code": "ERN", "scale": 2, "symbol": "ERN"},
    {"jurisdiction": "eswatini", "name": "lilangeni", "code": "SZL", "scale": 2, "symbol": "SZL"},
    {"jurisdiction": "ethiopia", "name": "birr", "code": "ETB", "scale": 2, "symbol": "ETB"},
    {"jurisdiction": "european_union", "name": "euro", "code": "EUR", "scale": 2, "symbol": "€"},
    {"jurisdiction": "falkland_islands", "name": "pound", "code": "FKP", "scale": 2, "symbol": "FKP"},
    {"jurisdiction": "fiji", "name": "dollar", "code": "FJD", "scale": 2, "symbol": "FJD"},
    {"jurisdiction": "gambia", "name": "dalasi", "code": "GMD", "scale": 2, "symbol": "GMD"},
    {"jurisdiction": "georgia", "name": "lari", "code": "GEL", "scale": 2, "symbol": "GEL"},
    {"jurisdiction": "ghana", "name": "cedi", "code": "GHS", "scale": 2, "symbol": "GHS"},
    {"jurisdiction": "gibraltar", "name": "pound", "code": "GIP", "scale": 2, "symbol": "GIP"},
    {"jurisdiction": "guatemala", "name": "quetzal", "code": "GTQ", "scale": 2, "symbol": "GTQ"},
    {"jurisdiction": "guinea", "name": "franc", "code": "GNF", "scale": 0, "symbol": "GNF"},
    {"jurisdiction": "guyana", "name": "dollar", "code": "GYD", "scale": 2, "symbol": "GYD"},
    {"jurisdiction": "haiti", "name": "gourde", "code": "HTG", "scale": 2, "symbol": "HTG"},
    {"jurisdiction": "honduras", "name": "lempira", "code": "HNL", "scale": 2, "symbol": "HNL"},
    {"jurisdiction": "hong_kong_sar_china", "name": "dollar", "code": "HKD", "scale": 2, "symbol": "HK$"},
    {"jurisdiction": "hungary", "name": "forint", "code": "HUF", "scale": 2, "symbol": "HUF"},
    {"jurisdiction": "iceland", "name": "krona", "code": "ISK", "scale": 0, "symbol": "ISK"},
    {"jurisdiction": "india", "name": "rupee", "code": "INR", "scale": 2, "symbol": "₹"},
    {"jurisdiction": "indonesia", "name": "rupiah", "code": "IDR", "scale": 2, "symbol": "IDR"},
    {"jurisdiction": "iran", "name": "rial", "code": "IRR", "scale": 2, "symbol": "IRR"},
    {"jurisdiction": "iraq", "name": "dinar", "code": "IQD", "scale": 3, "symbol": "IQD"},
    {"jurisdiction": "israel", "name": "shekel", "code": "ILS", "scale": 2, "symbol": "₪"},
    {"jurisdiction": "jamaica", "name": "dollar", "code": "JMD", "scale": 2, "symbol": "JMD"},
    {"jurisdiction": "japan", "name": "yen", "code": "JPY", "scale": 0, "symbol": "¥"},
    {"jurisdiction": "jordan", "name": "dinar", "code": "JOD", "scale": 3, "symbol": "JOD"},
    {"jurisdiction": "kazakhstan", "name": "tenge", "code": "KZT", "scale": 2, "symbol": "KZT"},
    {"jurisdiction": "kenya", "name": "shilling", "code": "KES", "scale": 2, "symbol": "KES"},
    {"jurisdiction": "kuwait", "name": "dinar", "code": "KWD", "scale": 3, "symbol": "KWD"},
    {"jurisdiction": "kyrgyzstan", "name": "som", "code": "KGS", "scale": 2, "symbol": "KGS"},
    {"jurisdiction": "laos", "name": "kip", "code": "LAK", "scale": 2, "symbol": "LAK"},
    {"jurisdiction": "lebanon", "name": "pound", "code": "LBP", "scale": 2, "symbol": "LBP"},
    {"jurisdiction": "lesotho", "name": "loti", "code": "LSL", "scale": 2, "symbol": "LSL"},
    {"jurisdiction": "liberia", "name": "dollar", "code": "LRD", "scale": 2, "symbol": "LRD"},
    {"jurisdiction": "libya", "name": "dinar", "code": "LYD", "scale": 3, "symbol": "LYD"},
    {"jurisdiction": "macao_sar_china", "name": "pataca", "code": "MOP", "scale": 2, "symbol": "MOP"},
    {"jurisdiction": "madagascar", "name": "ariary", "code": "MGA", "scale": 2, "symbol": "MGA"},
    {"jurisdiction": "malawi", "name": "kwacha", "code": "MWK", "scale": 2, "symbol": "MWK"},
    {"jurisdiction": "malaysia", "name": "ringgit", "code": "MYR", "scale": 2, "symbol": "MYR"},
    {"jurisdiction": "maldives", "name": "rufiyaa", "code": "MVR", "scale": 2, "symbol": "MVR"},
    {"jurisdiction": "mauritania", "name": "ouguiya", "code": "MRU", "scale": 2, "symbol": "MRU"},
    {"jurisdiction": "mauritius", "name": "rupee", "code": "MUR", "scale": 2, "symbol": "MUR"},
    {"jurisdiction": "mexico", "name": "peso", "code": "MXN", "scale": 2, "symbol": "MX$"},
    {"jurisdiction": "moldova", "name": "leu", "code": "MDL", "scale": 2, "symbol": "MDL"},
    {"jurisdiction": "mongolia", "name": "tugrik", "code": "MNT", "scale": 2, "symbol": "MNT"},
    {"jurisdiction": "morocco", "name": "dirham", "code": "MAD", "scale": 2, "symbol": "MAD"},
    {"jurisdiction": "mozambique", "name": "metical", "code": "MZN", "scale": 2, "symbol": "MZN"},
    {"jurisdiction": "myanmar_burma", "name": "kyat", "code": "MMK", "scale": 2, "symbol": "MMK"},
    {"jurisdiction": "namibia", "name": "dollar", "code": "NAD", "scale": 2, "symbol": "NAD"},
    {"jurisdiction": "nepal", "name": "rupee", "code": "NPR", "scale": 2, "symbol": "NPR"},
    {"jurisdiction": "new_zealand", "name": "dollar", "code": "NZD", "scale": 2, "symbol": "NZ$"},
    {"jurisdiction": "nicaragua", "name": "cordoba", "code": "NIO", "scale": 2, "symbol": "NIO"},
    {"jurisdiction": "nigeria", "name": "naira", "code": "NGN", "scale": 2, "symbol": "NGN"},
    {"jurisdiction": "north_korea", "name": "won", "code": "KPW", "scale": 2, "symbol": "KPW"},
    {"jurisdiction": "north_macedonia", "name": "denar", "code": "MKD", "scale": 2, "symbol": "MKD"},
    {"jurisdiction": "norway", "name": "krone", "code": "NOK", "scale": 2, "symbol": "NOK"},
    {"jurisdiction": "oman", "name": "rial", "code": "OMR", "scale": 3, "symbol": "OMR"},
    {"jurisdiction": "pakistan", "name": "rupee", "code": "PKR", "scale": 2, "symbol": "PKR"},
    {"jurisdiction": "panama", "name": "balboa", "code": "PAB", "scale": 2, "symbol": "PAB"},
    {"jurisdiction": "papua_new_guinea", "name": "kina", "code": "PGK", "scale": 2, "symbol": "PGK"},
    {"jurisdiction": "paraguay", "name": "guarani", "code": "PYG", "scale": 0, "symbol": "PYG"},
    {"jurisdiction": "peru", "name": "sol", "code": "PEN", "scale": 2, "symbol": "PEN"},
    {"jurisdiction": "philippines", "name": "peso", "code": "PHP", "scale": 2, "symbol": "₱"},
    {"jurisdiction": "poland", "name": "zloty", "code": "PLN", "scale": 2, "symbol": "PLN"},
    {"jurisdiction": "qatar", "name": "riyal", "code": "QAR", "scale": 2, "symbol": "QAR"},
    {"jurisdiction": "romania", "name": "leu", "code": "RON", "scale": 2, "symbol": "RON"},
    {"jurisdiction": "russia", "name": "ruble", "code": "RUB", "scale": 2, "symbol": "RUB"},
    {"jurisdiction": "rwanda", "name": "franc", "code": "RWF", "scale": 0, "symbol": "RWF"},
    {"jurisdiction": "samoa", "name": "tala", "code": "WST", "scale": 2, "symbol": "WST"},
    {"jurisdiction": "sao_tome_principe", "name": "dobra", "code": "STN", "scale": 2, "symbol": "STN"},
    {"jurisdiction": "saudi_arabia", "name": "riyal", "code": "SAR", "scale": 2, "symbol": "SAR"},
    {"jurisdiction": "serbia", "name": "dinar", "code": "RSD", "scale": 2, "symbol": "RSD"},
    {"jurisdiction": "seychelles", "name": "rupee", "code": "SCR", "scale": 2, "symbol": "SCR"},
    {"jurisdiction": "sierra_leone", "name": "leone", "code": "SLE", "scale": 2, "symbol": "SLE"},
    {"jurisdiction": "singapore", "name": "dollar", "code": "SGD", "scale": 2, "symbol": "SGD"},
    {"jurisdiction": "solomon_islands", "name": "dollar", "code": "SBD", "scale": 2, "symbol": "SBD"},
    {"jurisdiction": "somalia", "name": "shilling", "code": "SOS", "scale": 2, "symbol": "SOS"},
    {"jurisdiction": "south_africa", "name": "rand", "code": "ZAR", "scale": 2, "symbol": "ZAR"},
    {"jurisdiction": "south_korea", "name": "won", "code": "KRW", "scale": 0, "symbol": "₩"},
    {"jurisdiction": "south_sudan", "name": "pound", "code": "SSP", "scale": 2, "symbol": "SSP"},
    {"jurisdiction": "sri_lanka", "name": "rupee", "code": "LKR", "scale": 2, "symbol": "LKR"},
    {"jurisdiction": "st_helena", "name": "pound", "code": "SHP", "scale": 2, "symbol": "SHP"},
    {"jurisdiction": "sudan", "name": "pound", "code": "SDG", "scale": 2, "symbol": "SDG"},
    {"jurisdiction": "suriname", "name": "dollar", "code": "SRD", "scale": 2, "symbol": "SRD"},
    {"jurisdiction": "sweden", "name": "krona", "code": "SEK", "scale": 2, "symbol": "SEK"},
    {"jurisdiction": "switzerland", "name": "franc", "code": "CHF", "scale": 2, "symbol": "CHF"},
    {"jurisdiction": "syria", "name": "pound", "code": "SYP", "scale": 2, "symbol": "SYP"},
    {"jurisdiction": "taiwan", "name": "dollar", "code": "TWD", "scale": 2, "symbol": "NT$"},
    {"jurisdiction": "tajikistan", "name": "somoni", "code": "TJS", "scale": 2, "symbol": "TJS"},
    {"jurisdiction": "tanzania", "name": "shilling", "code": "TZS", "scale": 2, "symbol": "TZS"},
    {"jurisdiction": "thailand", "name": "baht", "code": "THB", "scale": 2, "symbol": "THB"},
    {"jurisdiction": "tonga", "name": "paanga", "code": "TOP", "scale": 2, "symbol": "TOP"},
    {"jurisdiction": "trinidad_tobago", "name": "dollar", "code": "TTD", "scale": 2, "symbol": "TTD"},
    {"jurisdiction": "tunisia", "name": "dinar", "code": "TND", "scale": 3, "symbol": "TND"},
    {"jurisdiction": "turkiye", "name": "lira", "code": "TRY", "scale": 2, "symbol": "TRY"},
    {"jurisdiction": "turkmenistan", "name": "manat", "code": "TMT", "scale": 2, "symbol": "TMT"},
    {"jurisdiction": "uganda", "name": "shilling", "code": "UGX", "scale": 0, "symbol": "UGX"},
    {"jurisdiction": "ukraine", "name": "hryvnia", "code": "UAH", "scale": 2, "symbol": "UAH"},
    {"jurisdiction": "united_arab_emirates", "name": "dirham", "code": "AED", "scale": 2, "symbol": "AED"},
    {"jurisdiction": "united_kingdom", "name": "sterling", "code": "GBP", "scale": 2, "symbol": "£"},
    {"jurisdiction": "united_states", "name": "dollar", "code": "USD", "scale": 2, "symbol": "$"},
    {"jurisdiction": "uruguay", "name": "peso", "code": "UYU", "scale": 2, "symbol": "UYU"},
    {"jurisdiction": "uzbekistan", "name": "som", "code": "UZS", "scale": 2, "symbol": "UZS"},
    {"jurisdiction": "vanuatu", "name": "vatu", "code": "VUV", "scale": 0, "symbol": "VUV"},
    {"jurisdiction": "venezuela", "name": "bolivar", "code": "VES", "scale": 2, "symbol": "VES"},
    {"jurisdiction": "vietnam", "name": "dong", "code": "VND", "scale": 0, "symbol": "₫"},
    {"jurisdiction": "west_african_cfa", "name": "franc", "code": "XOF", "scale": 0, "symbol": "F CFA"},
    {"jurisdiction": "yemen", "name": "rial", "code": "YER", "scale": 2, "symbol": "YER"},
    {"jurisdiction": "zambia", "name": "kwacha", "code": "ZMW", "scale": 2, "symbol": "ZMW"},
    {"jurisdiction": "zimbabwe", "name": "gold", "code": "ZWG", "scale": 2, "symbol": "ZWG"},
]

JURISDICTIONS = [
    "afghanistan",
    "albania",
    "algeria",
    "angola",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belize",
    "bermuda",
    "bhutan",
    "bolivia",
    "bosnia_herzegovina",
    "botswana",
    "brazil",
    "brunei",
    "bulgaria",
    "burundi",
    "cambodia",
    "canada",
    "cape_verde",
    "cayman_islands",
    "central_african_cfa",
    "cfp_franc",
    "chile",
    "china",
    "colombia",
    "comoros",
    "congo_kinshasa",
    "costa_rica",
    "cuba",
    "czechia",
    "denmark",
    "djibouti",
    "dominican_republic",
    "east_caribbean",
    "egypt",
    "eritrea",
    "eswatini",
    "ethiopia",
    "european_union",
    "falkland_islands",
    "fiji",
    "gambia",
    "georgia",
    "ghana",
    "gibraltar",
    "guatemala",
    "guinea",
    "guyana",
    "haiti",
    "honduras",
    "hong_kong_sar_china",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "israel",
    "jamaica",
    "japan",
    "jordan",
    "kazakhstan",
    "kenya",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "macao_sar_china",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mauritania",
    "mauritius",
    "mexico",
    "moldova",
    "mongolia",
    "morocco",
    "mozambique",
    "myanmar_burma",
    "namibia",
    "nepal",
    "new_zealand",
    "nicaragua",
    "nigeria",
    "north_korea",
    "north_macedonia",
    "norway",
    "oman",
    "pakistan",
    "panama",
    "papua_new_guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "qatar",
    "romania",
    "russia",
    "rwanda",
    "samoa",
    "sao_tome_principe",
    "saudi_arabia",
    "serbia",
    "seychelles",
    "sierra_leone",
    "singapore",
    "solomon_islands",
    "somalia",
    "south_africa",
    "south_korea",
    "south_sudan",
    "sri_lanka",
    "st_helena",
    "sudan",
    "suriname",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "tonga",
    "trinidad_tobago",
    "tunisia",
    "turkiye",
    "turkmenistan",
    "uganda",
    "ukraine",
    "united_arab_emirates",
    "united_kingdom",
    "united_states",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "venezuela",
    "vietnam",
    "west_african_cfa",
    "yemen",
    "zambia",
    "zimbabwe",
]
