"""Generated ISO-4217 currency data. Edit scripts/gen_currencies.py, not this."""

CURRENCIES = [
    {"jurisdiction": "afghanistan", "name": "afghani", "code": "AFN", "scale": 2, "symbol": "AFN", "historical": False, "start": "2002-10-07", "end": None},
    {"jurisdiction": "afghanistan", "name": "afghani_1927_2002", "code": "AFA", "scale": 2, "symbol": "AFA", "historical": True, "start": "1927-03-14", "end": "2002-12-31"},
    {"jurisdiction": "albania", "name": "lek", "code": "ALL", "scale": 2, "symbol": "ALL", "historical": False, "start": "1965-08-16", "end": None},
    {"jurisdiction": "albania", "name": "lek_1946_1965", "code": "ALK", "scale": 2, "symbol": "ALK", "historical": True, "start": "1946-11-01", "end": "1965-08-16"},
    {"jurisdiction": "algeria", "name": "dinar", "code": "DZD", "scale": 2, "symbol": "DZD", "historical": False, "start": "1964-04-01", "end": None},
    {"jurisdiction": "andorra", "name": "peseta", "code": "ADP", "scale": 2, "symbol": "ADP", "historical": True, "start": "1936-01-01", "end": "2001-12-31"},
    {"jurisdiction": "angola", "name": "kwanza", "code": "AOA", "scale": 2, "symbol": "AOA", "historical": False, "start": "1999-12-13", "end": None},
    {"jurisdiction": "angola", "name": "kwanza_1977_1991", "code": "AOK", "scale": 2, "symbol": "AOK", "historical": True, "start": "1977-01-08", "end": "1991-03-01"},
    {"jurisdiction": "angola", "name": "new_kwanza", "code": "AON", "scale": 2, "symbol": "AON", "historical": True, "start": "1990-09-25", "end": "2000-02-01"},
    {"jurisdiction": "angola", "name": "readjusted_kwanza", "code": "AOR", "scale": 2, "symbol": "AOR", "historical": True, "start": "1995-07-01", "end": "2000-02-01"},
    {"jurisdiction": "argentina", "name": "peso", "code": "ARS", "scale": 2, "symbol": "ARS", "historical": False, "start": "1992-01-01", "end": None},
    {"jurisdiction": "argentina", "name": "austral", "code": "ARA", "scale": 2, "symbol": "ARA", "historical": True, "start": "1985-06-14", "end": "1992-01-01"},
    {"jurisdiction": "argentina", "name": "ley", "code": "ARL", "scale": 2, "symbol": "ARL", "historical": True, "start": "1970-01-01", "end": "1983-06-01"},
    {"jurisdiction": "argentina", "name": "peso_1881_1970", "code": "ARM", "scale": 2, "symbol": "ARM", "historical": True, "start": "1881-11-05", "end": "1970-01-01"},
    {"jurisdiction": "argentina", "name": "peso_1983_1985", "code": "ARP", "scale": 2, "symbol": "ARP", "historical": True, "start": "1983-06-01", "end": "1985-06-14"},
    {"jurisdiction": "armenia", "name": "dram", "code": "AMD", "scale": 2, "symbol": "AMD", "historical": False, "start": "1993-11-22", "end": None},
    {"jurisdiction": "aruba", "name": "florin", "code": "AWG", "scale": 2, "symbol": "AWG", "historical": False, "start": "1986-01-01", "end": None},
    {"jurisdiction": "australia", "name": "dollar", "code": "AUD", "scale": 2, "symbol": "A$", "historical": False, "start": "1966-02-14", "end": None},
    {"jurisdiction": "austria", "name": "schilling", "code": "ATS", "scale": 2, "symbol": "ATS", "historical": True, "start": "1947-12-04", "end": "2002-02-28"},
    {"jurisdiction": "azerbaijan", "name": "manat", "code": "AZN", "scale": 2, "symbol": "AZN", "historical": False, "start": "2006-01-01", "end": None},
    {"jurisdiction": "azerbaijan", "name": "manat_1993_2006", "code": "AZM", "scale": 2, "symbol": "AZM", "historical": True, "start": "1993-11-22", "end": "2006-12-31"},
    {"jurisdiction": "bahamas", "name": "dollar", "code": "BSD", "scale": 2, "symbol": "BSD", "historical": False, "start": "1966-05-25", "end": None},
    {"jurisdiction": "bahrain", "name": "dinar", "code": "BHD", "scale": 3, "symbol": "BD", "historical": False, "start": "1965-10-16", "end": None},
    {"jurisdiction": "bangladesh", "name": "taka", "code": "BDT", "scale": 2, "symbol": "BDT", "historical": False, "start": "1972-01-01", "end": None},
    {"jurisdiction": "barbados", "name": "dollar", "code": "BBD", "scale": 2, "symbol": "BBD", "historical": False, "start": "1973-12-03", "end": None},
    {"jurisdiction": "belarus", "name": "ruble", "code": "BYN", "scale": 2, "symbol": "BYN", "historical": False, "start": "2016-07-01", "end": None},
    {"jurisdiction": "belarus", "name": "ruble_1994_2000", "code": "BYB", "scale": 2, "symbol": "BYB", "historical": True, "start": "1994-08-01", "end": "2000-12-31"},
    {"jurisdiction": "belarus", "name": "ruble_2000_2017", "code": "BYR", "scale": 2, "symbol": "BYR", "historical": True, "start": "2000-01-01", "end": "2017-01-01"},
    {"jurisdiction": "belgium", "name": "franc", "code": "BEF", "scale": 2, "symbol": "BEF", "historical": True, "start": "1831-02-07", "end": "2002-02-28"},
    {"jurisdiction": "belize", "name": "dollar", "code": "BZD", "scale": 2, "symbol": "BZD", "historical": False, "start": "1974-01-01", "end": None},
    {"jurisdiction": "bermuda", "name": "dollar", "code": "BMD", "scale": 2, "symbol": "BMD", "historical": False, "start": "1970-02-06", "end": None},
    {"jurisdiction": "bhutan", "name": "ngultrum", "code": "BTN", "scale": 2, "symbol": "BTN", "historical": False, "start": "1974-04-16", "end": None},
    {"jurisdiction": "bolivia", "name": "boliviano", "code": "BOB", "scale": 2, "symbol": "BOB", "historical": False, "start": "1987-01-01", "end": None},
    {"jurisdiction": "bolivia", "name": "boliviano_1863_1963", "code": "BOL", "scale": 2, "symbol": "BOL", "historical": True, "start": "1863-06-23", "end": "1963-01-01"},
    {"jurisdiction": "bolivia", "name": "peso", "code": "BOP", "scale": 2, "symbol": "BOP", "historical": True, "start": "1963-01-01", "end": "1986-12-31"},
    {"jurisdiction": "bosnia_herzegovina", "name": "mark", "code": "BAM", "scale": 2, "symbol": "BAM", "historical": False, "start": "1995-01-01", "end": None},
    {"jurisdiction": "bosnia_herzegovina", "name": "dinar_1992_1994", "code": "BAD", "scale": 2, "symbol": "BAD", "historical": True, "start": "1992-07-01", "end": "1994-08-15"},
    {"jurisdiction": "bosnia_herzegovina", "name": "new_dinar", "code": "BAN", "scale": 2, "symbol": "BAN", "historical": True, "start": "1994-08-15", "end": "1997-07-01"},
    {"jurisdiction": "botswana", "name": "pula", "code": "BWP", "scale": 2, "symbol": "BWP", "historical": False, "start": "1976-08-23", "end": None},
    {"jurisdiction": "brazil", "name": "real", "code": "BRL", "scale": 2, "symbol": "R$", "historical": False, "start": "1994-07-01", "end": None},
    {"jurisdiction": "brazil", "name": "cruzado_1986_1989", "code": "BRC", "scale": 2, "symbol": "BRC", "historical": True, "start": "1986-02-28", "end": "1989-01-15"},
    {"jurisdiction": "brazil", "name": "cruzeiro_1942_1967", "code": "BRZ", "scale": 2, "symbol": "BRZ", "historical": True, "start": "1942-11-01", "end": "1967-02-13"},
    {"jurisdiction": "brazil", "name": "cruzeiro_1990_1993", "code": "BRE", "scale": 2, "symbol": "BRE", "historical": True, "start": "1990-03-16", "end": "1993-08-01"},
    {"jurisdiction": "brazil", "name": "cruzeiro_1993_1994", "code": "BRR", "scale": 2, "symbol": "BRR", "historical": True, "start": "1993-08-01", "end": "1994-07-01"},
    {"jurisdiction": "brazil", "name": "new_cruzado", "code": "BRN", "scale": 2, "symbol": "BRN", "historical": True, "start": "1989-01-15", "end": "1990-03-16"},
    {"jurisdiction": "brazil", "name": "new_cruzeiro", "code": "BRB", "scale": 2, "symbol": "BRB", "historical": True, "start": "1967-02-13", "end": "1986-02-28"},
    {"jurisdiction": "brunei", "name": "dollar", "code": "BND", "scale": 2, "symbol": "BND", "historical": False, "start": "1967-06-12", "end": None},
    {"jurisdiction": "bulgaria", "name": "lev", "code": "BGN", "scale": 2, "symbol": "BGN", "historical": False, "start": "1999-07-05", "end": None},
    {"jurisdiction": "bulgaria", "name": "hard_lev", "code": "BGL", "scale": 2, "symbol": "BGL", "historical": True, "start": "1962-01-01", "end": "1999-07-05"},
    {"jurisdiction": "bulgaria", "name": "lev_1879_1952", "code": "BGO", "scale": 2, "symbol": "BGO", "historical": True, "start": "1879-07-08", "end": "1952-05-12"},
    {"jurisdiction": "bulgaria", "name": "socialist_lev", "code": "BGM", "scale": 2, "symbol": "BGM", "historical": True, "start": "1952-05-12", "end": "1962-01-01"},
    {"jurisdiction": "burundi", "name": "franc", "code": "BIF", "scale": 0, "symbol": "BIF", "historical": False, "start": "1964-05-19", "end": None},
    {"jurisdiction": "cambodia", "name": "riel", "code": "KHR", "scale": 2, "symbol": "KHR", "historical": False, "start": "1980-03-20", "end": None},
    {"jurisdiction": "canada", "name": "dollar", "code": "CAD", "scale": 2, "symbol": "CA$", "historical": False, "start": "1858-01-01", "end": None},
    {"jurisdiction": "cape_verde", "name": "escudo", "code": "CVE", "scale": 2, "symbol": "CVE", "historical": False, "start": "1914-01-01", "end": None},
    {"jurisdiction": "cayman_islands", "name": "dollar", "code": "KYD", "scale": 2, "symbol": "KYD", "historical": False, "start": "1971-01-01", "end": None},
    {"jurisdiction": "central_african_cfa", "name": "franc", "code": "XAF", "scale": 0, "symbol": "FCFA", "historical": False, "start": "1973-04-01", "end": None},
    {"jurisdiction": "cfp_franc", "name": "franc", "code": "XPF", "scale": 0, "symbol": "CFPF", "historical": False, "start": "1945-12-26", "end": None},
    {"jurisdiction": "chile", "name": "peso", "code": "CLP", "scale": 0, "symbol": "CLP", "historical": False, "start": "1975-09-29", "end": None},
    {"jurisdiction": "chile", "name": "escudo", "code": "CLE", "scale": 2, "symbol": "CLE", "historical": True, "start": "1960-01-01", "end": "1975-09-29"},
    {"jurisdiction": "china", "name": "yuan", "code": "CNY", "scale": 2, "symbol": "CN¥", "historical": False, "start": "1953-03-01", "end": None},
    {"jurisdiction": "colombia", "name": "peso", "code": "COP", "scale": 2, "symbol": "COP", "historical": False, "start": "1905-01-01", "end": None},
    {"jurisdiction": "comoros", "name": "franc", "code": "KMF", "scale": 0, "symbol": "KMF", "historical": False, "start": "1975-01-01", "end": None},
    {"jurisdiction": "congo_kinshasa", "name": "franc", "code": "CDF", "scale": 2, "symbol": "CDF", "historical": False, "start": "1998-07-01", "end": None},
    {"jurisdiction": "costa_rica", "name": "colon", "code": "CRC", "scale": 2, "symbol": "CRC", "historical": False, "start": "1896-10-26", "end": None},
    {"jurisdiction": "croatia", "name": "dinar", "code": "HRD", "scale": 2, "symbol": "HRD", "historical": True, "start": "1991-12-23", "end": "1995-01-01"},
    {"jurisdiction": "croatia", "name": "kuna", "code": "HRK", "scale": 2, "symbol": "HRK", "historical": True, "start": "1994-05-30", "end": "2023-01-14"},
    {"jurisdiction": "cuba", "name": "peso", "code": "CUP", "scale": 2, "symbol": "CUP", "historical": False, "start": "1859-01-01", "end": None},
    {"jurisdiction": "cuba", "name": "convertible_peso", "code": "CUC", "scale": 2, "symbol": "CUC", "historical": True, "start": "1994-01-01", "end": "2021-01-01"},
    {"jurisdiction": "cyprus", "name": "pound", "code": "CYP", "scale": 2, "symbol": "CYP", "historical": True, "start": "1914-09-10", "end": "2008-01-31"},
    {"jurisdiction": "czechia", "name": "koruna", "code": "CZK", "scale": 2, "symbol": "CZK", "historical": False, "start": "1993-01-01", "end": None},
    {"jurisdiction": "denmark", "name": "krone", "code": "DKK", "scale": 2, "symbol": "DKK", "historical": False, "start": "1873-05-27", "end": None},
    {"jurisdiction": "djibouti", "name": "franc", "code": "DJF", "scale": 0, "symbol": "DJF", "historical": False, "start": "1977-06-27", "end": None},
    {"jurisdiction": "dominican_republic", "name": "peso", "code": "DOP", "scale": 2, "symbol": "DOP", "historical": False, "start": "1947-10-01", "end": None},
    {"jurisdiction": "dutch_caribbean", "name": "guilder", "code": "XCG", "scale": 2, "symbol": "Cg.", "historical": False, "start": "2025-03-31", "end": None},
    {"jurisdiction": "east_caribbean", "name": "dollar", "code": "XCD", "scale": 2, "symbol": "EC$", "historical": False, "start": "1965-10-06", "end": None},
    {"jurisdiction": "ecuador", "name": "sucre", "code": "ECS", "scale": 2, "symbol": "ECS", "historical": True, "start": "1884-04-01", "end": "2000-10-02"},
    {"jurisdiction": "egypt", "name": "pound", "code": "EGP", "scale": 2, "symbol": "EGP", "historical": False, "start": "1885-11-14", "end": None},
    {"jurisdiction": "el_salvador", "name": "colon", "code": "SVC", "scale": 2, "symbol": "SVC", "historical": True, "start": "1919-11-11", "end": "2001-01-01"},
    {"jurisdiction": "equatorial_guinea", "name": "ekwele", "code": "GQE", "scale": 2, "symbol": "GQE", "historical": True, "start": "1975-07-07", "end": "1986-06-01"},
    {"jurisdiction": "eritrea", "name": "nakfa", "code": "ERN", "scale": 2, "symbol": "ERN", "historical": False, "start": "1997-11-08", "end": None},
    {"jurisdiction": "estonia", "name": "kroon", "code": "EEK", "scale": 2, "symbol": "EEK", "historical": True, "start": "1992-06-21", "end": "2010-12-31"},
    {"jurisdiction": "eswatini", "name": "lilangeni", "code": "SZL", "scale": 2, "symbol": "SZL", "historical": False, "start": "1974-09-06", "end": None},
    {"jurisdiction": "ethiopia", "name": "birr", "code": "ETB", "scale": 2, "symbol": "ETB", "historical": False, "start": "1976-09-15", "end": None},
    {"jurisdiction": "european_union", "name": "euro", "code": "EUR", "scale": 2, "symbol": "€", "historical": False, "start": "1999-01-01", "end": None},
    {"jurisdiction": "falkland_islands", "name": "pound", "code": "FKP", "scale": 2, "symbol": "FKP", "historical": False, "start": "1901-01-01", "end": None},
    {"jurisdiction": "fiji", "name": "dollar", "code": "FJD", "scale": 2, "symbol": "FJD", "historical": False, "start": "1969-01-13", "end": None},
    {"jurisdiction": "finland", "name": "markka", "code": "FIM", "scale": 2, "symbol": "FIM", "historical": True, "start": "1963-01-01", "end": "2002-02-28"},
    {"jurisdiction": "france", "name": "franc", "code": "FRF", "scale": 2, "symbol": "FRF", "historical": True, "start": "1959-01-01", "end": "2002-02-17"},
    {"jurisdiction": "gambia", "name": "dalasi", "code": "GMD", "scale": 2, "symbol": "GMD", "historical": False, "start": "1971-07-01", "end": None},
    {"jurisdiction": "georgia", "name": "lari", "code": "GEL", "scale": 2, "symbol": "GEL", "historical": False, "start": "1995-09-23", "end": None},
    {"jurisdiction": "georgia", "name": "larit", "code": "GEK", "scale": 2, "symbol": "GEK", "historical": True, "start": "1993-04-05", "end": "1995-09-25"},
    {"jurisdiction": "germany", "name": "mark", "code": "DEM", "scale": 2, "symbol": "DEM", "historical": True, "start": "1948-06-20", "end": "2002-05-15"},
    {"jurisdiction": "ghana", "name": "cedi", "code": "GHS", "scale": 2, "symbol": "GHS", "historical": False, "start": "2007-07-03", "end": None},
    {"jurisdiction": "ghana", "name": "cedi_1979_2007", "code": "GHC", "scale": 2, "symbol": "GHC", "historical": True, "start": "1979-03-09", "end": "2007-12-31"},
    {"jurisdiction": "gibraltar", "name": "pound", "code": "GIP", "scale": 2, "symbol": "GIP", "historical": False, "start": "1713-01-01", "end": None},
    {"jurisdiction": "greece", "name": "drachma", "code": "GRD", "scale": 2, "symbol": "GRD", "historical": True, "start": "1954-05-01", "end": "2002-02-28"},
    {"jurisdiction": "guatemala", "name": "quetzal", "code": "GTQ", "scale": 2, "symbol": "GTQ", "historical": False, "start": "1925-05-27", "end": None},
    {"jurisdiction": "guinea", "name": "franc", "code": "GNF", "scale": 0, "symbol": "GNF", "historical": False, "start": "1986-01-06", "end": None},
    {"jurisdiction": "guinea", "name": "syli", "code": "GNS", "scale": 2, "symbol": "GNS", "historical": True, "start": "1972-10-02", "end": "1986-01-06"},
    {"jurisdiction": "guinea_bissau", "name": "escudo", "code": "GWE", "scale": 2, "symbol": "GWE", "historical": True, "start": "1914-01-01", "end": "1976-02-28"},
    {"jurisdiction": "guinea_bissau", "name": "peso", "code": "GWP", "scale": 2, "symbol": "GWP", "historical": True, "start": "1976-02-28", "end": "1997-03-31"},
    {"jurisdiction": "guyana", "name": "dollar", "code": "GYD", "scale": 2, "symbol": "GYD", "historical": False, "start": "1966-05-26", "end": None},
    {"jurisdiction": "haiti", "name": "gourde", "code": "HTG", "scale": 2, "symbol": "HTG", "historical": False, "start": "1872-08-26", "end": None},
    {"jurisdiction": "honduras", "name": "lempira", "code": "HNL", "scale": 2, "symbol": "HNL", "historical": False, "start": "1926-04-03", "end": None},
    {"jurisdiction": "hong_kong_sar_china", "name": "dollar", "code": "HKD", "scale": 2, "symbol": "HK$", "historical": False, "start": "1895-02-02", "end": None},
    {"jurisdiction": "hungary", "name": "forint", "code": "HUF", "scale": 2, "symbol": "HUF", "historical": False, "start": "1946-07-23", "end": None},
    {"jurisdiction": "iceland", "name": "krona", "code": "ISK", "scale": 0, "symbol": "ISK", "historical": False, "start": "1981-01-01", "end": None},
    {"jurisdiction": "iceland", "name": "krona_1918_1981", "code": "ISJ", "scale": 2, "symbol": "ISJ", "historical": True, "start": "1918-12-01", "end": "1981-01-01"},
    {"jurisdiction": "india", "name": "rupee", "code": "INR", "scale": 2, "symbol": "₹", "historical": False, "start": "1835-08-17", "end": None},
    {"jurisdiction": "indonesia", "name": "rupiah", "code": "IDR", "scale": 2, "symbol": "IDR", "historical": False, "start": "1965-12-13", "end": None},
    {"jurisdiction": "iran", "name": "rial", "code": "IRR", "scale": 2, "symbol": "IRR", "historical": False, "start": "1932-05-13", "end": None},
    {"jurisdiction": "iraq", "name": "dinar", "code": "IQD", "scale": 3, "symbol": "IQD", "historical": False, "start": "1931-04-19", "end": None},
    {"jurisdiction": "ireland", "name": "pound", "code": "IEP", "scale": 2, "symbol": "IEP", "historical": True, "start": "1922-01-01", "end": "2002-02-09"},
    {"jurisdiction": "israel", "name": "shekel", "code": "ILS", "scale": 2, "symbol": "₪", "historical": False, "start": "1985-09-04", "end": None},
    {"jurisdiction": "israel", "name": "pound", "code": "ILP", "scale": 2, "symbol": "ILP", "historical": True, "start": "1948-08-16", "end": "1980-02-22"},
    {"jurisdiction": "israel", "name": "shekel_1980_1985", "code": "ILR", "scale": 2, "symbol": "ILR", "historical": True, "start": "1980-02-22", "end": "1985-09-04"},
    {"jurisdiction": "italy", "name": "lira", "code": "ITL", "scale": 2, "symbol": "ITL", "historical": True, "start": "1862-08-24", "end": "2002-02-28"},
    {"jurisdiction": "jamaica", "name": "dollar", "code": "JMD", "scale": 2, "symbol": "JMD", "historical": False, "start": "1969-09-08", "end": None},
    {"jurisdiction": "japan", "name": "yen", "code": "JPY", "scale": 0, "symbol": "¥", "historical": False, "start": "1871-06-01", "end": None},
    {"jurisdiction": "jordan", "name": "dinar", "code": "JOD", "scale": 3, "symbol": "JOD", "historical": False, "start": "1950-07-01", "end": None},
    {"jurisdiction": "kazakhstan", "name": "tenge", "code": "KZT", "scale": 2, "symbol": "KZT", "historical": False, "start": "1993-11-05", "end": None},
    {"jurisdiction": "kenya", "name": "shilling", "code": "KES", "scale": 2, "symbol": "KES", "historical": False, "start": "1966-09-14", "end": None},
    {"jurisdiction": "kuwait", "name": "dinar", "code": "KWD", "scale": 3, "symbol": "KWD", "historical": False, "start": "1961-04-01", "end": None},
    {"jurisdiction": "kyrgyzstan", "name": "som", "code": "KGS", "scale": 2, "symbol": "KGS", "historical": False, "start": "1993-05-10", "end": None},
    {"jurisdiction": "laos", "name": "kip", "code": "LAK", "scale": 2, "symbol": "LAK", "historical": False, "start": "1979-12-10", "end": None},
    {"jurisdiction": "latvia", "name": "lats", "code": "LVL", "scale": 2, "symbol": "LVL", "historical": True, "start": "1993-06-28", "end": "2013-12-31"},
    {"jurisdiction": "latvia", "name": "ruble", "code": "LVR", "scale": 2, "symbol": "LVR", "historical": True, "start": "1992-05-07", "end": "1993-10-17"},
    {"jurisdiction": "lebanon", "name": "pound", "code": "LBP", "scale": 2, "symbol": "LBP", "historical": False, "start": "1948-02-02", "end": None},
    {"jurisdiction": "lesotho", "name": "loti", "code": "LSL", "scale": 2, "symbol": "LSL", "historical": False, "start": "1980-01-22", "end": None},
    {"jurisdiction": "liberia", "name": "dollar", "code": "LRD", "scale": 2, "symbol": "LRD", "historical": False, "start": "1944-01-01", "end": None},
    {"jurisdiction": "libya", "name": "dinar", "code": "LYD", "scale": 3, "symbol": "LYD", "historical": False, "start": "1971-09-01", "end": None},
    {"jurisdiction": "lithuania", "name": "litas", "code": "LTL", "scale": 2, "symbol": "LTL", "historical": True, "start": "1993-06-25", "end": "2014-12-31"},
    {"jurisdiction": "lithuania", "name": "talonas", "code": "LTT", "scale": 2, "symbol": "LTT", "historical": True, "start": "1992-10-01", "end": "1993-06-25"},
    {"jurisdiction": "luxembourg", "name": "franc", "code": "LUF", "scale": 2, "symbol": "LUF", "historical": True, "start": "1944-09-04", "end": "2002-02-28"},
    {"jurisdiction": "macao_sar_china", "name": "pataca", "code": "MOP", "scale": 2, "symbol": "MOP", "historical": False, "start": "1901-01-01", "end": None},
    {"jurisdiction": "madagascar", "name": "ariary", "code": "MGA", "scale": 2, "symbol": "MGA", "historical": False, "start": "1983-11-01", "end": None},
    {"jurisdiction": "madagascar", "name": "franc", "code": "MGF", "scale": 2, "symbol": "MGF", "historical": True, "start": "1963-07-01", "end": "2004-12-31"},
    {"jurisdiction": "malawi", "name": "kwacha", "code": "MWK", "scale": 2, "symbol": "MWK", "historical": False, "start": "1971-02-15", "end": None},
    {"jurisdiction": "malaysia", "name": "ringgit", "code": "MYR", "scale": 2, "symbol": "MYR", "historical": False, "start": "1963-09-16", "end": None},
    {"jurisdiction": "maldives", "name": "rufiyaa", "code": "MVR", "scale": 2, "symbol": "MVR", "historical": False, "start": "1981-07-01", "end": None},
    {"jurisdiction": "maldives", "name": "rupee", "code": "MVP", "scale": 2, "symbol": "MVP", "historical": True, "start": "1947-01-01", "end": "1981-07-01"},
    {"jurisdiction": "mali", "name": "franc", "code": "MLF", "scale": 2, "symbol": "MLF", "historical": True, "start": "1962-07-02", "end": "1984-08-31"},
    {"jurisdiction": "malta", "name": "lira", "code": "MTL", "scale": 2, "symbol": "MTL", "historical": True, "start": "1968-06-07", "end": "2008-01-31"},
    {"jurisdiction": "malta", "name": "pound", "code": "MTP", "scale": 2, "symbol": "MTP", "historical": True, "start": "1914-08-13", "end": "1968-06-07"},
    {"jurisdiction": "mauritania", "name": "ouguiya", "code": "MRU", "scale": 2, "symbol": "MRU", "historical": False, "start": "2018-01-01", "end": None},
    {"jurisdiction": "mauritania", "name": "ouguiya_1973_2018", "code": "MRO", "scale": 2, "symbol": "MRO", "historical": True, "start": "1973-06-29", "end": "2018-06-30"},
    {"jurisdiction": "mauritius", "name": "rupee", "code": "MUR", "scale": 2, "symbol": "MUR", "historical": False, "start": "1934-04-01", "end": None},
    {"jurisdiction": "mexico", "name": "peso", "code": "MXN", "scale": 2, "symbol": "MX$", "historical": False, "start": "1993-01-01", "end": None},
    {"jurisdiction": "mexico", "name": "silver_peso", "code": "MXP", "scale": 2, "symbol": "MXP", "historical": True, "start": "1822-01-01", "end": "1992-12-31"},
    {"jurisdiction": "moldova", "name": "leu", "code": "MDL", "scale": 2, "symbol": "MDL", "historical": False, "start": "1993-11-29", "end": None},
    {"jurisdiction": "moldova", "name": "cupon", "code": "MDC", "scale": 2, "symbol": "MDC", "historical": True, "start": "1992-06-01", "end": "1993-11-29"},
    {"jurisdiction": "monaco", "name": "franc", "code": "MCF", "scale": 2, "symbol": "MCF", "historical": True, "start": "1960-01-01", "end": "2002-02-17"},
    {"jurisdiction": "mongolia", "name": "tugrik", "code": "MNT", "scale": 2, "symbol": "MNT", "historical": False, "start": "1915-03-01", "end": None},
    {"jurisdiction": "morocco", "name": "dirham", "code": "MAD", "scale": 2, "symbol": "MAD", "historical": False, "start": "1959-10-17", "end": None},
    {"jurisdiction": "morocco", "name": "franc", "code": "MAF", "scale": 2, "symbol": "MAF", "historical": True, "start": "1881-01-01", "end": "1959-10-17"},
    {"jurisdiction": "mozambique", "name": "metical", "code": "MZN", "scale": 2, "symbol": "MZN", "historical": False, "start": "2006-07-01", "end": None},
    {"jurisdiction": "mozambique", "name": "escudo", "code": "MZE", "scale": 2, "symbol": "MZE", "historical": True, "start": "1975-06-25", "end": "1980-06-16"},
    {"jurisdiction": "mozambique", "name": "metical_1980_2006", "code": "MZM", "scale": 2, "symbol": "MZM", "historical": True, "start": "1980-06-16", "end": "2006-12-31"},
    {"jurisdiction": "myanmar_burma", "name": "kyat", "code": "MMK", "scale": 2, "symbol": "MMK", "historical": False, "start": "1989-06-18", "end": None},
    {"jurisdiction": "namibia", "name": "dollar", "code": "NAD", "scale": 2, "symbol": "NAD", "historical": False, "start": "1993-01-01", "end": None},
    {"jurisdiction": "nepal", "name": "rupee", "code": "NPR", "scale": 2, "symbol": "NPR", "historical": False, "start": "1933-01-01", "end": None},
    {"jurisdiction": "netherlands", "name": "guilder", "code": "NLG", "scale": 2, "symbol": "NLG", "historical": True, "start": "1813-01-01", "end": "2002-02-28"},
    {"jurisdiction": "new_zealand", "name": "dollar", "code": "NZD", "scale": 2, "symbol": "NZ$", "historical": False, "start": "1967-07-10", "end": None},
    {"jurisdiction": "nicaragua", "name": "cordoba", "code": "NIO", "scale": 2, "symbol": "NIO", "historical": False, "start": "1991-04-30", "end": None},
    {"jurisdiction": "nicaragua", "name": "cordoba_1988_1991", "code": "NIC", "scale": 2, "symbol": "NIC", "historical": True, "start": "1988-02-15", "end": "1991-04-30"},
    {"jurisdiction": "nigeria", "name": "naira", "code": "NGN", "scale": 2, "symbol": "NGN", "historical": False, "start": "1973-01-01", "end": None},
    {"jurisdiction": "north_korea", "name": "won", "code": "KPW", "scale": 2, "symbol": "KPW", "historical": False, "start": "1959-04-17", "end": None},
    {"jurisdiction": "north_macedonia", "name": "denar", "code": "MKD", "scale": 2, "symbol": "MKD", "historical": False, "start": "1993-05-20", "end": None},
    {"jurisdiction": "north_macedonia", "name": "denar_1992_1993", "code": "MKN", "scale": 2, "symbol": "MKN", "historical": True, "start": "1992-04-26", "end": "1993-05-20"},
    {"jurisdiction": "norway", "name": "krone", "code": "NOK", "scale": 2, "symbol": "NOK", "historical": False, "start": "1905-06-07", "end": None},
    {"jurisdiction": "oman", "name": "rial", "code": "OMR", "scale": 3, "symbol": "OMR", "historical": False, "start": "1972-11-11", "end": None},
    {"jurisdiction": "pakistan", "name": "rupee", "code": "PKR", "scale": 2, "symbol": "PKR", "historical": False, "start": "1948-04-01", "end": None},
    {"jurisdiction": "panama", "name": "balboa", "code": "PAB", "scale": 2, "symbol": "PAB", "historical": False, "start": "1903-11-04", "end": None},
    {"jurisdiction": "papua_new_guinea", "name": "kina", "code": "PGK", "scale": 2, "symbol": "PGK", "historical": False, "start": "1975-09-16", "end": None},
    {"jurisdiction": "paraguay", "name": "guarani", "code": "PYG", "scale": 0, "symbol": "PYG", "historical": False, "start": "1943-11-01", "end": None},
    {"jurisdiction": "peru", "name": "sol", "code": "PEN", "scale": 2, "symbol": "PEN", "historical": False, "start": "1991-07-01", "end": None},
    {"jurisdiction": "peru", "name": "inti", "code": "PEI", "scale": 2, "symbol": "PEI", "historical": True, "start": "1985-02-01", "end": "1991-07-01"},
    {"jurisdiction": "peru", "name": "sol_1863_1985", "code": "PES", "scale": 2, "symbol": "PES", "historical": True, "start": "1863-02-14", "end": "1985-02-01"},
    {"jurisdiction": "philippines", "name": "peso", "code": "PHP", "scale": 2, "symbol": "₱", "historical": False, "start": "1946-07-04", "end": None},
    {"jurisdiction": "poland", "name": "zloty", "code": "PLN", "scale": 2, "symbol": "PLN", "historical": False, "start": "1995-01-01", "end": None},
    {"jurisdiction": "poland", "name": "zloty_1950_1994", "code": "PLZ", "scale": 2, "symbol": "PLZ", "historical": True, "start": "1950-10-28", "end": "1994-12-31"},
    {"jurisdiction": "portugal", "name": "escudo", "code": "PTE", "scale": 2, "symbol": "PTE", "historical": True, "start": "1911-05-22", "end": "2002-02-28"},
    {"jurisdiction": "qatar", "name": "riyal", "code": "QAR", "scale": 2, "symbol": "QAR", "historical": False, "start": "1973-05-19", "end": None},
    {"jurisdiction": "romania", "name": "leu", "code": "RON", "scale": 2, "symbol": "RON", "historical": False, "start": "2005-07-01", "end": None},
    {"jurisdiction": "romania", "name": "leu_1952_2006", "code": "ROL", "scale": 2, "symbol": "ROL", "historical": True, "start": "1952-01-28", "end": "2006-12-31"},
    {"jurisdiction": "russia", "name": "ruble", "code": "RUB", "scale": 2, "symbol": "RUB", "historical": False, "start": "1999-01-01", "end": None},
    {"jurisdiction": "russia", "name": "ruble_1991_1998", "code": "RUR", "scale": 2, "symbol": "RUR", "historical": True, "start": "1991-12-25", "end": "1998-12-31"},
    {"jurisdiction": "rwanda", "name": "franc", "code": "RWF", "scale": 0, "symbol": "RWF", "historical": False, "start": "1964-05-19", "end": None},
    {"jurisdiction": "samoa", "name": "tala", "code": "WST", "scale": 2, "symbol": "WST", "historical": False, "start": "1967-07-10", "end": None},
    {"jurisdiction": "sao_tome_principe", "name": "dobra", "code": "STN", "scale": 2, "symbol": "STN", "historical": False, "start": "2018-01-01", "end": None},
    {"jurisdiction": "sao_tome_principe", "name": "dobra_1977_2017", "code": "STD", "scale": 2, "symbol": "STD", "historical": True, "start": "1977-09-08", "end": "2017-12-31"},
    {"jurisdiction": "saudi_arabia", "name": "riyal", "code": "SAR", "scale": 2, "symbol": "SAR", "historical": False, "start": "1952-10-22", "end": None},
    {"jurisdiction": "serbia", "name": "dinar", "code": "RSD", "scale": 2, "symbol": "RSD", "historical": False, "start": "2006-10-25", "end": None},
    {"jurisdiction": "seychelles", "name": "rupee", "code": "SCR", "scale": 2, "symbol": "SCR", "historical": False, "start": "1903-11-01", "end": None},
    {"jurisdiction": "sierra_leone", "name": "leone", "code": "SLE", "scale": 2, "symbol": "SLE", "historical": False, "start": "2022-07-01", "end": None},
    {"jurisdiction": "sierra_leone", "name": "leone_1964_2023", "code": "SLL", "scale": 2, "symbol": "SLL", "historical": True, "start": "1964-08-04", "end": "2023-12-31"},
    {"jurisdiction": "singapore", "name": "dollar", "code": "SGD", "scale": 2, "symbol": "SGD", "historical": False, "start": "1967-06-12", "end": None},
    {"jurisdiction": "slovakia", "name": "koruna", "code": "SKK", "scale": 2, "symbol": "SKK", "historical": True, "start": "1992-12-31", "end": "2009-01-01"},
    {"jurisdiction": "slovenia", "name": "tolar", "code": "SIT", "scale": 2, "symbol": "SIT", "historical": True, "start": "1992-10-07", "end": "2007-01-14"},
    {"jurisdiction": "solomon_islands", "name": "dollar", "code": "SBD", "scale": 2, "symbol": "SBD", "historical": False, "start": "1977-10-24", "end": None},
    {"jurisdiction": "somalia", "name": "shilling", "code": "SOS", "scale": 2, "symbol": "SOS", "historical": False, "start": "1960-07-01", "end": None},
    {"jurisdiction": "south_africa", "name": "rand", "code": "ZAR", "scale": 2, "symbol": "ZAR", "historical": False, "start": "1961-02-14", "end": None},
    {"jurisdiction": "south_korea", "name": "won", "code": "KRW", "scale": 0, "symbol": "₩", "historical": False, "start": "1962-06-10", "end": None},
    {"jurisdiction": "south_korea", "name": "hwan", "code": "KRH", "scale": 2, "symbol": "KRH", "historical": True, "start": "1953-02-15", "end": "1962-06-10"},
    {"jurisdiction": "south_korea", "name": "won_1945_1953", "code": "KRO", "scale": 2, "symbol": "KRO", "historical": True, "start": "1945-08-15", "end": "1953-02-15"},
    {"jurisdiction": "south_sudan", "name": "pound", "code": "SSP", "scale": 2, "symbol": "SSP", "historical": False, "start": "2011-07-18", "end": None},
    {"jurisdiction": "spain", "name": "peseta", "code": "ESP", "scale": 2, "symbol": "ESP", "historical": True, "start": "1800-01-01", "end": "2002-02-28"},
    {"jurisdiction": "sri_lanka", "name": "rupee", "code": "LKR", "scale": 2, "symbol": "LKR", "historical": False, "start": "1978-05-22", "end": None},
    {"jurisdiction": "st_helena", "name": "pound", "code": "SHP", "scale": 2, "symbol": "SHP", "historical": False, "start": "1917-02-15", "end": None},
    {"jurisdiction": "sudan", "name": "pound", "code": "SDG", "scale": 2, "symbol": "SDG", "historical": False, "start": "2007-01-10", "end": None},
    {"jurisdiction": "sudan", "name": "dinar", "code": "SDD", "scale": 2, "symbol": "SDD", "historical": True, "start": "1992-06-08", "end": "2007-06-30"},
    {"jurisdiction": "sudan", "name": "pound_1957_1998", "code": "SDP", "scale": 2, "symbol": "SDP", "historical": True, "start": "1957-04-08", "end": "1998-06-01"},
    {"jurisdiction": "suriname", "name": "dollar", "code": "SRD", "scale": 2, "symbol": "SRD", "historical": False, "start": "2004-01-01", "end": None},
    {"jurisdiction": "suriname", "name": "guilder", "code": "SRG", "scale": 2, "symbol": "SRG", "historical": True, "start": "1940-05-10", "end": "2003-12-31"},
    {"jurisdiction": "sweden", "name": "krona", "code": "SEK", "scale": 2, "symbol": "SEK", "historical": False, "start": "1873-05-27", "end": None},
    {"jurisdiction": "switzerland", "name": "franc", "code": "CHF", "scale": 2, "symbol": "CHF", "historical": False, "start": "1799-03-17", "end": None},
    {"jurisdiction": "syria", "name": "pound", "code": "SYP", "scale": 2, "symbol": "SYP", "historical": False, "start": "1948-01-01", "end": None},
    {"jurisdiction": "taiwan", "name": "dollar", "code": "TWD", "scale": 2, "symbol": "NT$", "historical": False, "start": "1949-06-15", "end": None},
    {"jurisdiction": "tajikistan", "name": "somoni", "code": "TJS", "scale": 2, "symbol": "TJS", "historical": False, "start": "2000-10-26", "end": None},
    {"jurisdiction": "tajikistan", "name": "ruble", "code": "TJR", "scale": 2, "symbol": "TJR", "historical": True, "start": "1995-05-10", "end": "2000-10-25"},
    {"jurisdiction": "tanzania", "name": "shilling", "code": "TZS", "scale": 2, "symbol": "TZS", "historical": False, "start": "1966-06-14", "end": None},
    {"jurisdiction": "thailand", "name": "baht", "code": "THB", "scale": 2, "symbol": "THB", "historical": False, "start": "1928-04-15", "end": None},
    {"jurisdiction": "tonga", "name": "paanga", "code": "TOP", "scale": 2, "symbol": "TOP", "historical": False, "start": "1966-02-14", "end": None},
    {"jurisdiction": "trinidad_tobago", "name": "dollar", "code": "TTD", "scale": 2, "symbol": "TTD", "historical": False, "start": "1964-01-01", "end": None},
    {"jurisdiction": "tunisia", "name": "dinar", "code": "TND", "scale": 3, "symbol": "TND", "historical": False, "start": "1958-11-01", "end": None},
    {"jurisdiction": "turkiye", "name": "lira", "code": "TRY", "scale": 2, "symbol": "TRY", "historical": False, "start": "2005-01-01", "end": None},
    {"jurisdiction": "turkiye", "name": "lira_1922_2005", "code": "TRL", "scale": 2, "symbol": "TRL", "historical": True, "start": "1922-11-01", "end": "2005-12-31"},
    {"jurisdiction": "turkmenistan", "name": "manat", "code": "TMT", "scale": 2, "symbol": "TMT", "historical": False, "start": "2009-01-01", "end": None},
    {"jurisdiction": "turkmenistan", "name": "manat_1993_2009", "code": "TMM", "scale": 2, "symbol": "TMM", "historical": True, "start": "1993-11-01", "end": "2009-01-01"},
    {"jurisdiction": "uganda", "name": "shilling", "code": "UGX", "scale": 0, "symbol": "UGX", "historical": False, "start": "1987-05-15", "end": None},
    {"jurisdiction": "uganda", "name": "shilling_1966_1987", "code": "UGS", "scale": 2, "symbol": "UGS", "historical": True, "start": "1966-08-15", "end": "1987-05-15"},
    {"jurisdiction": "ukraine", "name": "hryvnia", "code": "UAH", "scale": 2, "symbol": "UAH", "historical": False, "start": "1996-09-02", "end": None},
    {"jurisdiction": "ukraine", "name": "karbovanets", "code": "UAK", "scale": 2, "symbol": "UAK", "historical": True, "start": "1992-11-13", "end": "1993-10-17"},
    {"jurisdiction": "united_arab_emirates", "name": "dirham", "code": "AED", "scale": 2, "symbol": "AED", "historical": False, "start": "1973-05-19", "end": None},
    {"jurisdiction": "united_kingdom", "name": "sterling", "code": "GBP", "scale": 2, "symbol": "£", "historical": False, "start": "1694-07-27", "end": None},
    {"jurisdiction": "united_states", "name": "dollar", "code": "USD", "scale": 2, "symbol": "$", "historical": False, "start": "1792-01-01", "end": None},
    {"jurisdiction": "uruguay", "name": "peso", "code": "UYU", "scale": 2, "symbol": "UYU", "historical": False, "start": "1993-03-01", "end": None},
    {"jurisdiction": "uruguay", "name": "peso_1975_1993", "code": "UYP", "scale": 2, "symbol": "UYP", "historical": True, "start": "1975-07-01", "end": "1993-03-01"},
    {"jurisdiction": "uzbekistan", "name": "som", "code": "UZS", "scale": 2, "symbol": "UZS", "historical": False, "start": "1994-07-01", "end": None},
    {"jurisdiction": "vanuatu", "name": "vatu", "code": "VUV", "scale": 0, "symbol": "VUV", "historical": False, "start": "1981-01-01", "end": None},
    {"jurisdiction": "venezuela", "name": "bolivar", "code": "VES", "scale": 2, "symbol": "VES", "historical": False, "start": "2018-08-20", "end": None},
    {"jurisdiction": "venezuela", "name": "bolivar_1871_2008", "code": "VEB", "scale": 2, "symbol": "VEB", "historical": True, "start": "1871-05-11", "end": "2008-06-30"},
    {"jurisdiction": "venezuela", "name": "bolivar_2008_2018", "code": "VEF", "scale": 2, "symbol": "VEF", "historical": True, "start": "2008-01-01", "end": "2018-08-20"},
    {"jurisdiction": "vietnam", "name": "dong", "code": "VND", "scale": 0, "symbol": "₫", "historical": False, "start": "1985-09-14", "end": None},
    {"jurisdiction": "vietnam", "name": "dong_1978_1985", "code": "VNN", "scale": 2, "symbol": "VNN", "historical": True, "start": "1978-05-03", "end": "1985-09-14"},
    {"jurisdiction": "west_african_cfa", "name": "franc", "code": "XOF", "scale": 0, "symbol": "F CFA", "historical": False, "start": "1958-11-24", "end": None},
    {"jurisdiction": "yemen", "name": "rial", "code": "YER", "scale": 2, "symbol": "YER", "historical": False, "start": "1990-05-22", "end": None},
    {"jurisdiction": "zambia", "name": "kwacha", "code": "ZMW", "scale": 2, "symbol": "ZMW", "historical": False, "start": "2013-01-01", "end": None},
    {"jurisdiction": "zambia", "name": "kwacha_1968_2013", "code": "ZMK", "scale": 2, "symbol": "ZMK", "historical": True, "start": "1968-01-16", "end": "2013-01-01"},
    {"jurisdiction": "zimbabwe", "name": "gold", "code": "ZWG", "scale": 2, "symbol": "ZWG", "historical": False, "start": "2024-06-25", "end": None},
    {"jurisdiction": "zimbabwe", "name": "dollar_1980_2008", "code": "ZWD", "scale": 2, "symbol": "ZWD", "historical": True, "start": "1980-04-18", "end": "2008-08-01"},
    {"jurisdiction": "zimbabwe", "name": "dollar_2008_2009", "code": "ZWR", "scale": 2, "symbol": "ZWR", "historical": True, "start": "2008-08-01", "end": "2009-02-02"},
    {"jurisdiction": "zimbabwe", "name": "dollar_2009_2024", "code": "ZWL", "scale": 2, "symbol": "ZWL", "historical": True, "start": "2009-02-02", "end": "2024-08-31"},
]

JURISDICTIONS = [
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "bermuda",
    "bhutan",
    "bolivia",
    "bosnia_herzegovina",
    "botswana",
    "brazil",
    "brunei",
    "bulgaria",
    "burundi",
    "cambodia",
    "canada",
    "cape_verde",
    "cayman_islands",
    "central_african_cfa",
    "cfp_franc",
    "chile",
    "china",
    "colombia",
    "comoros",
    "congo_kinshasa",
    "costa_rica",
    "croatia",
    "cuba",
    "cyprus",
    "czechia",
    "denmark",
    "djibouti",
    "dominican_republic",
    "dutch_caribbean",
    "east_caribbean",
    "ecuador",
    "egypt",
    "el_salvador",
    "equatorial_guinea",
    "eritrea",
    "estonia",
    "eswatini",
    "ethiopia",
    "european_union",
    "falkland_islands",
    "fiji",
    "finland",
    "france",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "guatemala",
    "guinea",
    "guinea_bissau",
    "guyana",
    "haiti",
    "honduras",
    "hong_kong_sar_china",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "israel",
    "italy",
    "jamaica",
    "japan",
    "jordan",
    "kazakhstan",
    "kenya",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "lithuania",
    "luxembourg",
    "macao_sar_china",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "mauritania",
    "mauritius",
    "mexico",
    "moldova",
    "monaco",
    "mongolia",
    "morocco",
    "mozambique",
    "myanmar_burma",
    "namibia",
    "nepal",
    "netherlands",
    "new_zealand",
    "nicaragua",
    "nigeria",
    "north_korea",
    "north_macedonia",
    "norway",
    "oman",
    "pakistan",
    "panama",
    "papua_new_guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "qatar",
    "romania",
    "russia",
    "rwanda",
    "samoa",
    "sao_tome_principe",
    "saudi_arabia",
    "serbia",
    "seychelles",
    "sierra_leone",
    "singapore",
    "slovakia",
    "slovenia",
    "solomon_islands",
    "somalia",
    "south_africa",
    "south_korea",
    "south_sudan",
    "spain",
    "sri_lanka",
    "st_helena",
    "sudan",
    "suriname",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "tonga",
    "trinidad_tobago",
    "tunisia",
    "turkiye",
    "turkmenistan",
    "uganda",
    "ukraine",
    "united_arab_emirates",
    "united_kingdom",
    "united_states",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "venezuela",
    "vietnam",
    "west_african_cfa",
    "yemen",
    "zambia",
    "zimbabwe",
]

#: The identifier each currency is BOUND to: its everyday
#: word when that word names exactly one CURRENT currency,
#: otherwise its lowercase ISO 4217 code. The word survives
#: as `_name` for display either way.
CURRENCY_BINDINGS = {
    "ADP": "adp",
    "AED": "aed",
    "AFA": "afghani_1927_2002",
    "AFN": "afghani",
    "ALK": "lek_1946_1965",
    "ALL": "lek",
    "AMD": "dram",
    "AOA": "kwanza",
    "AOK": "kwanza_1977_1991",
    "AON": "new_kwanza",
    "AOR": "readjusted_kwanza",
    "ARA": "austral",
    "ARL": "ley",
    "ARM": "peso_1881_1970",
    "ARP": "peso_1983_1985",
    "ARS": "ars",
    "ATS": "schilling",
    "AUD": "aud",
    "AWG": "florin",
    "AZM": "manat_1993_2006",
    "AZN": "azn",
    "BAD": "dinar_1992_1994",
    "BAM": "mark",
    "BAN": "new_dinar",
    "BBD": "bbd",
    "BDT": "taka",
    "BEF": "bef",
    "BGL": "hard_lev",
    "BGM": "socialist_lev",
    "BGN": "lev",
    "BGO": "lev_1879_1952",
    "BHD": "bhd",
    "BIF": "bif",
    "BMD": "bmd",
    "BND": "bnd",
    "BOB": "boliviano",
    "BOL": "boliviano_1863_1963",
    "BOP": "bop",
    "BRB": "new_cruzeiro",
    "BRC": "cruzado_1986_1989",
    "BRE": "cruzeiro_1990_1993",
    "BRL": "real",
    "BRN": "new_cruzado",
    "BRR": "cruzeiro_1993_1994",
    "BRZ": "cruzeiro_1942_1967",
    "BSD": "bsd",
    "BTN": "ngultrum",
    "BWP": "pula",
    "BYB": "ruble_1994_2000",
    "BYN": "byn",
    "BYR": "ruble_2000_2017",
    "BZD": "bzd",
    "CAD": "cad",
    "CDF": "cdf",
    "CHF": "chf",
    "CLE": "cle",
    "CLP": "clp",
    "CNY": "yuan",
    "COP": "cop",
    "CRC": "colon",
    "CUC": "convertible_peso",
    "CUP": "cup",
    "CVE": "escudo",
    "CYP": "cyp",
    "CZK": "koruna",
    "DEM": "dem",
    "DJF": "djf",
    "DKK": "dkk",
    "DOP": "dop",
    "DZD": "dzd",
    "ECS": "sucre",
    "EEK": "kroon",
    "EGP": "egp",
    "ERN": "nakfa",
    "ESP": "esp",
    "ETB": "birr",
    "EUR": "euro",
    "FIM": "markka",
    "FJD": "fjd",
    "FKP": "fkp",
    "FRF": "frf",
    "GBP": "sterling",
    "GEK": "larit",
    "GEL": "lari",
    "GHC": "cedi_1979_2007",
    "GHS": "cedi",
    "GIP": "gip",
    "GMD": "dalasi",
    "GNF": "gnf",
    "GNS": "syli",
    "GQE": "ekwele",
    "GRD": "drachma",
    "GTQ": "quetzal",
    "GWE": "gwe",
    "GWP": "gwp",
    "GYD": "gyd",
    "HKD": "hkd",
    "HNL": "lempira",
    "HRD": "hrd",
    "HRK": "kuna",
    "HTG": "gourde",
    "HUF": "forint",
    "IDR": "rupiah",
    "IEP": "iep",
    "ILP": "ilp",
    "ILR": "shekel_1980_1985",
    "ILS": "shekel",
    "INR": "inr",
    "IQD": "iqd",
    "IRR": "irr",
    "ISJ": "krona_1918_1981",
    "ISK": "isk",
    "ITL": "itl",
    "JMD": "jmd",
    "JOD": "jod",
    "JPY": "yen",
    "KES": "kes",
    "KGS": "kgs",
    "KHR": "riel",
    "KMF": "kmf",
    "KPW": "kpw",
    "KRH": "hwan",
    "KRO": "won_1945_1953",
    "KRW": "krw",
    "KWD": "kwd",
    "KYD": "kyd",
    "KZT": "tenge",
    "LAK": "kip",
    "LBP": "lbp",
    "LKR": "lkr",
    "LRD": "lrd",
    "LSL": "loti",
    "LTL": "litas",
    "LTT": "talonas",
    "LUF": "luf",
    "LVL": "lats",
    "LVR": "lvr",
    "LYD": "lyd",
    "MAD": "mad",
    "MAF": "maf",
    "MCF": "mcf",
    "MDC": "cupon",
    "MDL": "mdl",
    "MGA": "ariary",
    "MGF": "mgf",
    "MKD": "denar",
    "MKN": "denar_1992_1993",
    "MLF": "mlf",
    "MMK": "kyat",
    "MNT": "tugrik",
    "MOP": "pataca",
    "MRO": "ouguiya_1973_2018",
    "MRU": "ouguiya",
    "MTL": "mtl",
    "MTP": "mtp",
    "MUR": "mur",
    "MVP": "mvp",
    "MVR": "rufiyaa",
    "MWK": "mwk",
    "MXN": "mxn",
    "MXP": "silver_peso",
    "MYR": "ringgit",
    "MZE": "mze",
    "MZM": "metical_1980_2006",
    "MZN": "metical",
    "NAD": "nad",
    "NGN": "naira",
    "NIC": "cordoba_1988_1991",
    "NIO": "cordoba",
    "NLG": "nlg",
    "NOK": "nok",
    "NPR": "npr",
    "NZD": "nzd",
    "OMR": "omr",
    "PAB": "balboa",
    "PEI": "inti",
    "PEN": "sol",
    "PES": "sol_1863_1985",
    "PGK": "kina",
    "PHP": "php",
    "PKR": "pkr",
    "PLN": "zloty",
    "PLZ": "zloty_1950_1994",
    "PTE": "pte",
    "PYG": "guarani",
    "QAR": "qar",
    "ROL": "leu_1952_2006",
    "RON": "ron",
    "RSD": "rsd",
    "RUB": "rub",
    "RUR": "ruble_1991_1998",
    "RWF": "rwf",
    "SAR": "sar",
    "SBD": "sbd",
    "SCR": "scr",
    "SDD": "sdd",
    "SDG": "sdg",
    "SDP": "pound_1957_1998",
    "SEK": "sek",
    "SGD": "sgd",
    "SHP": "shp",
    "SIT": "tolar",
    "SKK": "skk",
    "SLE": "leone",
    "SLL": "leone_1964_2023",
    "SOS": "sos",
    "SRD": "srd",
    "SRG": "srg",
    "SSP": "ssp",
    "STD": "dobra_1977_2017",
    "STN": "dobra",
    "SVC": "svc",
    "SYP": "syp",
    "SZL": "lilangeni",
    "THB": "baht",
    "TJR": "tjr",
    "TJS": "somoni",
    "TMM": "manat_1993_2009",
    "TMT": "tmt",
    "TND": "tnd",
    "TOP": "paanga",
    "TRL": "lira_1922_2005",
    "TRY": "lira",
    "TTD": "ttd",
    "TWD": "twd",
    "TZS": "tzs",
    "UAH": "hryvnia",
    "UAK": "karbovanets",
    "UGS": "shilling_1966_1987",
    "UGX": "ugx",
    "USD": "usd",
    "UYP": "peso_1975_1993",
    "UYU": "uyu",
    "UZS": "uzs",
    "VEB": "bolivar_1871_2008",
    "VEF": "bolivar_2008_2018",
    "VES": "bolivar",
    "VND": "dong",
    "VNN": "dong_1978_1985",
    "VUV": "vatu",
    "WST": "tala",
    "XAF": "xaf",
    "XCD": "xcd",
    "XCG": "guilder",
    "XOF": "xof",
    "XPF": "xpf",
    "YER": "yer",
    "ZAR": "rand",
    "ZMK": "kwacha_1968_2013",
    "ZMW": "zmw",
    "ZWD": "dollar_1980_2008",
    "ZWG": "gold",
    "ZWL": "dollar_2009_2024",
    "ZWR": "dollar_2008_2009",
}

#: Curated subunit WORDS (ISO 4217 carries the scale, not the word).
MINOR_UNIT_WORDS = {
    "AUD": "cent",
    "EUR": "cent",
    "GBP": "penny",
    "THB": "satang",
    "USD": "cent",
}

#: The names actually bound: a word shared by more than one currency
#: takes its ISO code as a prefix, a unique word stays bare.
MINOR_UNITS = {
    "AUD": "aud_cent",
    "EUR": "eur_cent",
    "GBP": "penny",
    "THB": "satang",
    "USD": "usd_cent",
}
